import { describe, expect, it } from "vitest";
import type { Metric, MetricValue, Venue } from "@/lib/types";
import { buildPerformancePressureShadow } from "./performancePressureShadow";
const mv=(metric:Metric,venue:Venue,value:number,sampleSize=10):MetricValue=>({metric,venue,value,sampleSize,lowConfidence:false,breakdown:[]});
const profile=(venue:Venue,xg:number,xga:number)=>[mv("SHOTS",venue,14),mv("SHOTS_ON_TARGET",venue,5),mv("SHOTS_INSIDE_BOX",venue,8),mv("XG",venue,xg),mv("XG_AGAINST",venue,xga),mv("GOALS_AGAINST",venue,xga),mv("POSSESSION",venue,54),mv("CORNERS",venue,5.5)];
describe("performance pressure shadow v3",()=>{
  it("freezes a coherent expected match shape",()=>{const r=buildPerformancePressureShadow({homeValues:profile("HOME",1.8,1.1),awayValues:profile("AWAY",1.4,1.6),currentLambdaHome:1.7,currentLambdaAway:1.2,currentOver25:.58});expect(r.version).toBe(3);expect(r.currentOver25).toBe(.58);expect(r.expectedMatchShape.home.shots.value).toBeGreaterThan(0);expect(r.expectedMatchShape.home.shots.interval?.level).toBe(.8);expect(r.expectedMatchShape.home.chanceShare.value!+r.expectedMatchShape.away.chanceShare.value!).toBeCloseTo(1);expect(r.expectedMatchShape.home.possessionShare.value!+r.expectedMatchShape.away.possessionShare.value!).toBeCloseTo(1);expect(r.opennessScore).toBeLessThan(100);expect(r.coverage.ratio).toBe(1)});
  it("falls back to a low-confidence context baseline when team volume is missing",()=>{const r=buildPerformancePressureShadow({homeValues:[mv("XG","HOME",1.2)],awayValues:[mv("XG_AGAINST","AWAY",1.3)],currentLambdaHome:1,currentLambdaAway:1,currentOver25:.4});expect(r.coverage.ratio).toBeLessThan(.5);expect(r.expectedMatchShape.home.shots.value).toBeGreaterThanOrEqual(8);expect(r.expectedMatchShape.home.shots.value).toBeLessThanOrEqual(14);expect(r.expectedMatchShape.home.shots.confidence).toBeLessThan(.25);expect(r.expectedMatchShape.home.xg.confidence).toBeLessThan(.5)});
  it("shows dependency on the weaker side",()=>{const r=buildPerformancePressureShadow({homeValues:profile("HOME",1.2,1.2),awayValues:profile("AWAY",1.8,1.2),currentLambdaHome:1.25,currentLambdaAway:1.99,currentOver25:.63});expect(r.dependencyRisk.weakerSide).toBe("HOME");expect(r.dependencyRisk.level).not.toBe("LOW")});
  it("does not turn very low historical xG per shot into 32 shots",()=>{const lowQuality=[mv("SHOTS","HOME",13),mv("SHOTS_ON_TARGET","HOME",5.6),mv("SHOTS_INSIDE_BOX","HOME",9.6),mv("XG","HOME",.69),mv("POSSESSION","HOME",53),mv("CORNERS","HOME",4.5)];const r=buildPerformancePressureShadow({homeValues:lowQuality,awayValues:profile("AWAY",2.2,1.4),currentLambdaHome:1.72,currentLambdaAway:1.2,currentOver25:.58,context:"LEAGUE"});expect(r.expectedMatchShape.home.shots.value).toBeLessThan(20);expect(r.expectedMatchShape.home.shots.value).not.toBeCloseTo(32.5)});
  it("keeps conditional counts coherent and context guardrails explicit",()=>{const extreme=profile("HOME",4.5,2).map(row=>row.metric==="SHOTS"?{...row,value:50}:row);const r=buildPerformancePressureShadow({homeValues:extreme,awayValues:profile("AWAY",1,1),currentLambdaHome:4,currentLambdaAway:.7,currentOver25:.8,context:"LEAGUE"});const side=r.expectedMatchShape.home;expect(side.shots.value).toBeLessThanOrEqual(28);expect(side.shotsOnTarget.value).toBeLessThanOrEqual(side.shots.value!);expect(side.shotsInsideBox.value).toBeLessThanOrEqual(side.shots.value!);expect(side.shots.warnings).toContain("CLIPPED_OUTLIER")});
});
