import type{Metric,MetricValue,Venue}from"@/lib/types";
import{gridProbs}from"@/lib/stats/predict";
import{buildPerformancePressureShadow,type ExpectedMatchShapeSide,type PerformancePressureShadow,type PressureContext}from"./performancePressureShadow";
import{PRESSURE_V4_ARTIFACT}from"./performancePressureShadowV4";
export const PERFORMANCE_PRESSURE_V5_VERSION=5;
export type PressureV5Market="OVER_25"|"BTTS_YES"|"TEAM_HOME_05"|"TEAM_HOME_15"|"TEAM_AWAY_05"|"TEAM_AWAY_15";
export interface PerformancePressureShadowV5 extends Omit<PerformancePressureShadow,"version"|"method">{version:5;method:"MATCHUP_VOLUME_SHADOW_V5";candidate:true;artifactVersion:1;allowedVolumeCoverage:number;featureCoverage:number;fallbacks:string[];goalLambda:{home:number;away:number};marketProbabilities:Record<PressureV5Market,number>;runtimeMs:number}
const clamp=(v:number,min=0,max=1)=>Math.min(max,Math.max(min,v)),round=(v:number,d=3)=>Number(v.toFixed(d));
const metric=(values:MetricValue[],name:Metric,venue:Venue)=>values.find(v=>v.metric===name&&v.venue===venue)?.value??values.find(v=>v.metric===name&&v.venue==="TOTAL")?.value??null;
const share=(a:number,b:number)=>a+b>0?a/(a+b):.5;
function openness(value:number,context:PressureContext){const knots=PRESSURE_V4_ARTIFACT[context].openness,scores=[1,15,35,60,82,97];if(value<=knots[0])return 1;for(let i=1;i<knots.length;i++)if(value<=knots[i])return round(scores[i-1]+(scores[i]-scores[i-1])*(value-knots[i-1])/(knots[i]-knots[i-1]),0);return 99}
function matchup(side:ExpectedMatchShapeSide,opponent:MetricValue[],venue:Venue){const allowed=metric(opponent,"SHOTS_AGAINST",venue),allowedSot=metric(opponent,"SHOTS_ON_TARGET_AGAINST",venue),allowedBox=metric(opponent,"SHOTS_INSIDE_BOX_AGAINST",venue),base=side.shots.value;if(base==null||allowed==null)return{side,available:0};const shots=clamp(base*.65+Math.sqrt(Math.max(1,base)*Math.max(1,allowed))*.35,2,32),sot=allowedSot==null?side.shotsOnTarget.value:Math.min(shots,(side.shotsOnTarget.value??shots*.33)*.7+allowedSot*.3),box=allowedBox==null?side.shotsInsideBox.value:Math.min(shots,(side.shotsInsideBox.value??shots*.64)*.7+allowedBox*.3),scale=shots/base,adjust=(value:number|null)=>value==null?null:round(value*scale,1);return{available:1,side:{...side,shots:{...side.shots,value:round(shots,1),source:"CALIBRATED_VOLUME",warnings:[...(side.shots.warnings??[]),"MATCHUP_ALLOWED_VOLUME"]},shotsOnTarget:{...side.shotsOnTarget,value:adjust(sot)},shotsInsideBox:{...side.shotsInsideBox,value:adjust(box)}}}}
const atLeast=(lambda:number,line:.5|1.5)=>line===.5?1-Math.exp(-lambda):1-Math.exp(-lambda)*(1+lambda);
export function buildPerformancePressureShadowV5(input:{homeValues:MetricValue[];awayValues:MetricValue[];currentLambdaHome:number;currentLambdaAway:number;currentOver25:number;context?:PressureContext;capturedAt?:Date}):PerformancePressureShadowV5{const started=Date.now(),context=input.context??"LEAGUE",base=buildPerformancePressureShadow(input),h=matchup(base.expectedMatchShape.home,input.awayValues,"AWAY"),a=matchup(base.expectedMatchShape.away,input.homeValues,"HOME"),lambdaShare=share(input.currentLambdaHome,input.currentLambdaAway),volumeShare=share((h.side.xg.value??0)+(h.side.shotsOnTarget.value??0)*.12+(h.side.shotsInsideBox.value??0)*.05,(a.side.xg.value??0)+(a.side.shotsOnTarget.value??0)*.12+(a.side.shotsInsideBox.value??0)*.05),homeShare=clamp(lambdaShare*.85+volumeShare*.15,.08,.92),total=(h.side.shots.value??12)+(a.side.shots.value??12),open=openness(total,context),weaker=homeShare<=.5?"HOME":"AWAY",weak=Math.min(homeShare,1-homeShare),volumeScale=clamp(total/24,.75,1.3),qualityHome=clamp((h.side.shotQuality.value??.105)/.105,.8,1.2),qualityAway=clamp((a.side.shotQuality.value??.105)/.105,.8,1.2),lambdaHome=round(input.currentLambdaHome*.72+input.currentLambdaHome*volumeScale*qualityHome*.28),lambdaAway=round(input.currentLambdaAway*.72+input.currentLambdaAway*volumeScale*qualityAway*.28),probs=gridProbs(lambdaHome,lambdaAway),allowedCoverage=(h.available+a.available)/2,fallbacks:string[]=[];if(allowedCoverage<1)fallbacks.push("MISSING_ALLOWED_VOLUME");if(base.coverage.ratio<.75)fallbacks.push("LOW_FEATURE_COVERAGE");if([...h.side.shots.warnings??[],...a.side.shots.warnings??[]].includes("CLIPPED_OUTLIER"))fallbacks.push("CLIPPED_OUTLIER");h.side.chanceShare={...h.side.chanceShare,value:round(homeShare)};a.side.chanceShare={...a.side.chanceShare,value:round(1-homeShare)};return{...base,version:5,method:"MATCHUP_VOLUME_SHADOW_V5",candidate:true,artifactVersion:1,opennessScore:open,allowedVolumeCoverage:allowedCoverage,featureCoverage:round((base.coverage.ratio*3+allowedCoverage)/4),fallbacks,goalLambda:{home:lambdaHome,away:lambdaAway},marketProbabilities:{OVER_25:round(probs.over25),BTTS_YES:round(probs.bttsYes),TEAM_HOME_05:round(atLeast(lambdaHome,.5)),TEAM_HOME_15:round(atLeast(lambdaHome,1.5)),TEAM_AWAY_05:round(atLeast(lambdaAway,.5)),TEAM_AWAY_15:round(atLeast(lambdaAway,1.5))},runtimeMs:Date.now()-started,expectedMatchShape:{...base.expectedMatchShape,home:h.side,away:a.side,openness:open,opennessLabel:open<25?"LOW":open<75?"NORMAL":open<90?"HIGH":"EXTREME",weakerSide:weaker,weakerChanceShare:round(weak)},dependencyRisk:{...base.dependencyRisk,weakerSide:weaker,weakerShare:round(weak),level:weak>=.38?"HIGH":weak>=.28?"MEDIUM":"LOW"}}}
