import type { Metric, MetricValue, Venue } from "@/lib/types";
import { gridProbs } from "@/lib/stats/predict";

export const PERFORMANCE_PRESSURE_SHADOW_VERSION = 1;
export interface PerformancePressureSide { shots:number|null; shotsOnTarget:number|null; shotsInsideBox:number|null; xg:number|null; xgAgainst:number|null; possession:number|null; corners:number|null; shotQuality:number|null; onTargetRate:number|null; boxShotRate:number|null; pressureCapability:number|null; pressureResistance:number|null; expectedPressure:number|null; shotLambda:number|null; sample:number }
export interface PerformancePressureShadow { version:1; method:"HEURISTIC_SHADOW_V1"; capturedAt:string; home:PerformancePressureSide; away:PerformancePressureSide; opennessScore:number|null; currentTotalLambda:number; shotTotalLambda:number|null; blendedTotalLambda:number|null; currentOver25:number; shadowOver25:number|null; over25Delta:number|null; dependencyRisk:{ weakerSide:"HOME"|"AWAY"; weakerShare:number; probabilityOverWithoutWeakerSide:number; level:"LOW"|"MEDIUM"|"HIGH" }; coverage:{available:number;expected:number;ratio:number} }
const clamp=(v:number,min=0,max=1)=>Math.min(max,Math.max(min,v));
const round=(v:number,d=3)=>Number(v.toFixed(d));
function metric(values:MetricValue[],name:Metric,venue:Venue){const exact=values.find(x=>x.metric===name&&x.venue===venue),total=values.find(x=>x.metric===name&&x.venue==="TOTAL"),picked=exact?.value!=null?exact:total;return{value:picked?.value??null,sample:picked?.sampleSize??0}}
function score(parts:Array<[number|null,number,number]>){let sum=0,weight=0;for(const[v,ref,w]of parts){if(v==null||!Number.isFinite(v))continue;sum+=clamp(v/ref,0,1.6)*w;weight+=w}return weight?round(clamp(sum/weight/1.25)*100,1):null}
function side(values:MetricValue[],venue:Venue,opponent:MetricValue[],opponentVenue:Venue):PerformancePressureSide{
  const shots=metric(values,"SHOTS",venue),sot=metric(values,"SHOTS_ON_TARGET",venue),box=metric(values,"SHOTS_INSIDE_BOX",venue),xg=metric(values,"XG",venue),possession=metric(values,"POSSESSION",venue),corners=metric(values,"CORNERS",venue),xga=metric(opponent,"XG_AGAINST",opponentVenue),ga=metric(opponent,"GOALS_AGAINST",opponentVenue);
  const capability=score([[xg.value,1.45,.34],[sot.value,4.5,.24],[box.value,7.5,.2],[shots.value,13,.1],[corners.value,5,.08],[possession.value,50,.04]]),vulnerability=score([[xga.value,1.45,.7],[ga.value,1.35,.3]]);
  const creative=[xg.value,sot.value==null?null:sot.value*.28,box.value==null?null:box.value*.16,shots.value==null?null:shots.value*.105].filter((v):v is number=>v!=null),own=creative.length?creative.reduce((a,b)=>a+b,0)/creative.length:null;
  const samples=[shots.sample,sot.sample,box.sample,xg.sample].filter(n=>n>0);
  return{shots:shots.value,shotsOnTarget:sot.value,shotsInsideBox:box.value,xg:xg.value,xgAgainst:xga.value,possession:possession.value,corners:corners.value,shotQuality:xg.value!=null&&shots.value?round(xg.value/shots.value):null,onTargetRate:sot.value!=null&&shots.value?round(sot.value/shots.value):null,boxShotRate:box.value!=null&&shots.value?round(box.value/shots.value):null,pressureCapability:capability,pressureResistance:vulnerability==null?null:round(100-vulnerability,1),expectedPressure:capability==null?null:round(clamp(capability/100*((vulnerability??50)/50),0,1.4)*100,1),shotLambda:own==null?null:round(xga.value==null?own:Math.sqrt(Math.max(.05,own)*Math.max(.05,xga.value))),sample:samples.length?Math.min(...samples):0};
}
function atLeast(lambda:number,goals:number){let term=Math.exp(-lambda),sum=term;for(let i=1;i<goals;i++){term*=lambda/i;sum+=term}return clamp(1-sum)}
export function buildPerformancePressureShadow(input:{homeValues:MetricValue[];awayValues:MetricValue[];currentLambdaHome:number;currentLambdaAway:number;currentOver25:number;capturedAt?:Date}):PerformancePressureShadow{
  const home=side(input.homeValues,"HOME",input.awayValues,"AWAY"),away=side(input.awayValues,"AWAY",input.homeValues,"HOME"),shotTotal=home.shotLambda!=null&&away.shotLambda!=null?home.shotLambda+away.shotLambda:null,bh=home.shotLambda==null?null:input.currentLambdaHome*.65+home.shotLambda*.35,ba=away.shotLambda==null?null:input.currentLambdaAway*.65+away.shotLambda*.35,shadow=bh!=null&&ba!=null?gridProbs(bh,ba).over25:null;
  const available=[home.shots,home.shotsOnTarget,home.shotsInsideBox,home.xg,home.xgAgainst,home.possession,away.shots,away.shotsOnTarget,away.shotsInsideBox,away.xg,away.xgAgainst,away.possession].filter(v=>v!=null).length,weaker=input.currentLambdaHome<=input.currentLambdaAway?"HOME":"AWAY",weak=Math.min(input.currentLambdaHome,input.currentLambdaAway),strong=Math.max(input.currentLambdaHome,input.currentLambdaAway),share=weak/Math.max(.01,weak+strong),solo=atLeast(strong,3),level=share>=.36&&solo<.35?"HIGH":share>=.28&&solo<.45?"MEDIUM":"LOW",pressures=[home.expectedPressure,away.expectedPressure];
  return{version:1,method:"HEURISTIC_SHADOW_V1",capturedAt:(input.capturedAt??new Date()).toISOString(),home,away,opennessScore:pressures.every((v):v is number=>v!=null)?round(clamp((pressures[0]!+pressures[1]!)/180)*100,1):null,currentTotalLambda:round(input.currentLambdaHome+input.currentLambdaAway),shotTotalLambda:shotTotal==null?null:round(shotTotal),blendedTotalLambda:bh==null||ba==null?null:round(bh+ba),currentOver25:round(input.currentOver25),shadowOver25:shadow==null?null:round(shadow),over25Delta:shadow==null?null:round(shadow-input.currentOver25),dependencyRisk:{weakerSide:weaker,weakerShare:round(share),probabilityOverWithoutWeakerSide:round(solo),level},coverage:{available,expected:12,ratio:round(available/12)}};
}
