import type { PressureContext } from "./performancePressureShadow";

export const PRESSURE_REPLAY_CACHE_KEY = "model-audit:pressure-v3:historical-replay";
export const PRESSURE_V4_REPLAY_CACHE_KEY = "model-audit:pressure-v4:historical-replay";
export const PRESSURE_V5_REPLAY_CACHE_KEY = "model-audit:pressure-v5:historical-replay";
export const PRESSURE_REPLAY_VERSION = 1;
export type ReplayFidelity = "FULL" | "PARTIAL";
export type ReplayMetricKey = "shots" | "shotsOnTarget" | "shotsInsideBox" | "xg" | "corners";
export interface PressureReplayObservation { fixtureId:number;date:string;context:PressureContext;fidelity:ReplayFidelity;side:"HOME"|"AWAY";expected:Partial<Record<ReplayMetricKey,number>>;actual:Partial<Record<ReplayMetricKey,number>>;intervals:Partial<Record<ReplayMetricKey,{low:number;high:number}>>;openness:number;expectedChanceShare:number;actualChanceShare:number|null;expectedWeaker:boolean;actualContributionShare:number|null;historicalTeamShots:number|null;contextShots:number;reconstructedV2Shots:number|null;sample:number }
export interface PressureReplayReport { reportVersion:number;pressureVersion:3;generatedAt:string;dataFrom:string|null;dataThrough:string|null;fixtureCount:number;sideCount:number;fidelity:{full:number;partial:number};leakageViolations:number;metrics:Array<{key:ReplayMetricKey;n:number;mae:number|null;coverage80:number|null}>;shotBenchmarks:{n:number;v3Mae:number|null;teamMeanMae:number|null;contextMae:number|null;reconstructedV2Mae:number|null};dominance:{n:number;correctRate:number|null;maeShare:number|null};weakerSide:{n:number;maeContributionShare:number|null};openness:Array<{bucket:string;from:number;to:number;n:number;actualShots:number|null;actualXg:number|null}>;opennessMonotonic:boolean|null;contexts:Array<{context:PressureContext;n:number;shotsMae:number|null;shotsCoverage80:number|null}>;verdict:"PASS"|"REVIEW"|"INSUFFICIENT_DATA";notes:string[] }
const mean=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:null;
const mae=(rows:PressureReplayObservation[],key:ReplayMetricKey,source:"expected"|"team"|"context"|"v2"="expected")=>{const e=rows.flatMap(r=>{const a=r.actual[key],p=source==="expected"?r.expected[key]:source==="team"?r.historicalTeamShots:source==="context"?r.contextShots:r.reconstructedV2Shots;return a==null||p==null?[]:[Math.abs(p-a)]});return{n:e.length,value:mean(e)}};
export function summarizePressureReplay(rows:PressureReplayObservation[],generatedAt=new Date()):PressureReplayReport{
 const metrics=(["shots","shotsOnTarget","shotsInsideBox","xg","corners"]as ReplayMetricKey[]).map(key=>{const e=mae(rows,key),c=rows.flatMap(r=>r.actual[key]==null||!r.intervals[key]?[]:[r.actual[key]!>=r.intervals[key]!.low&&r.actual[key]!<=r.intervals[key]!.high?1:0]);return{key,n:e.n,mae:e.value,coverage80:mean(c)}});
 const v3=mae(rows,"shots"),team=mae(rows,"shots","team"),context=mae(rows,"shots","context"),v2=mae(rows,"shots","v2");const home=rows.filter(r=>r.side==="HOME"&&r.actualChanceShare!=null);const correct=home.map(r=>r.expectedChanceShare>=.45&&r.expectedChanceShare<=.55?(r.actualChanceShare!>=.45&&r.actualChanceShare!<=.55?1:0):((r.expectedChanceShare>.55)===(r.actualChanceShare!>.55)?1:0));const weak=rows.filter(r=>r.expectedWeaker&&r.actualContributionShare!=null);
 const openness=([[0,29],[30,49],[50,69],[70,89],[90,99]]as const).map(([from,to])=>{const cohort=home.filter(r=>r.openness>=from&&r.openness<=to),totals=cohort.map(h=>{const a=rows.find(r=>r.fixtureId===h.fixtureId&&r.side==="AWAY");return{shots:h.actual.shots!=null&&a?.actual.shots!=null?h.actual.shots+a.actual.shots:null,xg:h.actual.xg!=null&&a?.actual.xg!=null?h.actual.xg+a.actual.xg:null}});return{bucket:`${from}-${to}`,from,to,n:cohort.length,actualShots:mean(totals.flatMap(r=>r.shots==null?[]:[r.shots])),actualXg:mean(totals.flatMap(r=>r.xg==null?[]:[r.xg]))}}),pop=openness.filter(r=>r.n>=20&&r.actualShots!=null),monotonic=pop.length<3?null:pop.every((r,i)=>i===0||r.actualShots!>=pop[i-1].actualShots!-.25);
 const contexts=(["LEAGUE","EURO_CUP","NATIONAL"]as PressureContext[]).map(ctx=>{const cohort=rows.filter(r=>r.context===ctx),e=mae(cohort,"shots"),c=cohort.flatMap(r=>r.actual.shots==null||!r.intervals.shots?[]:[r.actual.shots>=r.intervals.shots.low&&r.actual.shots<=r.intervals.shots.high?1:0]);return{context:ctx,n:e.n,shotsMae:e.value,shotsCoverage80:mean(c)}});const coverage=metrics[0].coverage80,enough=v3.n>=200,pass=enough&&v3.value!=null&&team.value!=null&&context.value!=null&&v3.value<team.value&&v3.value<context.value&&coverage!=null&&coverage>=.75&&coverage<=.85&&monotonic===true,dates=rows.map(r=>r.date).sort();
 return{reportVersion:PRESSURE_REPLAY_VERSION,pressureVersion:3,generatedAt:generatedAt.toISOString(),dataFrom:dates[0]??null,dataThrough:dates.at(-1)??null,fixtureCount:new Set(rows.map(r=>r.fixtureId)).size,sideCount:rows.length,fidelity:{full:rows.filter(r=>r.fidelity==="FULL").length,partial:rows.filter(r=>r.fidelity==="PARTIAL").length},leakageViolations:0,metrics,shotBenchmarks:{n:v3.n,v3Mae:v3.value,teamMeanMae:team.value,contextMae:context.value,reconstructedV2Mae:v2.value},dominance:{n:home.length,correctRate:mean(correct),maeShare:mean(home.map(r=>Math.abs(r.expectedChanceShare-r.actualChanceShare!)))},weakerSide:{n:weak.length,maeContributionShare:mean(weak.map(r=>Math.abs(r.expectedChanceShare-r.actualContributionShare!)))},openness,opennessMonotonic:monotonic,contexts,verdict:!enough?"INSUFFICIENT_DATA":pass?"PASS":"REVIEW",notes:["FULL používá předzápasovou λ uloženou před výkopem; PARTIAL ji rekonstruuje pouze z dřívějších výkonů.","V2 je rekonstrukce starého xG/shot principu, nikoli uložený historický snapshot.","Replay používá pouze řádky před hodnoceným výkopem a nevolá externí API."]};
}
