ALTER TABLE "DirectorPlayer" ADD COLUMN "squadLevel" TEXT NOT NULL DEFAULT 'SENIOR', ADD COLUMN "homegrownClubId" TEXT, ADD COLUMN "academyJoinedDay" INTEGER, ADD COLUMN "developmentFocus" TEXT;
CREATE INDEX "DirectorPlayer_clubId_squadLevel_idx" ON "DirectorPlayer"("clubId","squadLevel");

CREATE TABLE "DirectorStadiumZone" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "kind" TEXT NOT NULL, "name" TEXT NOT NULL, "level" INTEGER NOT NULL DEFAULT 1, "capacity" INTEGER NOT NULL DEFAULT 0, "condition" DOUBLE PRECISION NOT NULL DEFAULT 65, "quality" DOUBLE PRECISION NOT NULL DEFAULT 50, "operatingCost" INTEGER NOT NULL DEFAULT 0, "revenuePotential" INTEGER NOT NULL DEFAULT 0, "temporaryCapacity" INTEGER, "metadata" JSONB NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "DirectorStadiumZone_careerId_clubId_kind_key" ON "DirectorStadiumZone"("careerId","clubId","kind"); CREATE INDEX "DirectorStadiumZone_careerId_clubId_idx" ON "DirectorStadiumZone"("careerId","clubId");

CREATE TABLE "DirectorCapitalProject" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "kind" TEXT NOT NULL, "title" TEXT NOT NULL, "phase" TEXT NOT NULL DEFAULT 'INTENT', "status" TEXT NOT NULL DEFAULT 'ACTIVE', "startedDay" INTEGER NOT NULL, "targetDay" INTEGER, "completedDay" INTEGER, "costMin" INTEGER NOT NULL, "costMax" INTEGER NOT NULL, "approvedCost" INTEGER, "spent" INTEGER NOT NULL DEFAULT 0, "contingency" INTEGER NOT NULL DEFAULT 0, "operatingCost" INTEGER NOT NULL DEFAULT 0, "capacityDelta" INTEGER NOT NULL DEFAULT 0, "temporaryCapacity" INTEGER, "benefit" JSONB NOT NULL DEFAULT '{}', "riskProfile" JSONB NOT NULL DEFAULT '{}', "history" JSONB NOT NULL DEFAULT '[]', "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "DirectorCapitalProject_careerId_clubId_status_idx" ON "DirectorCapitalProject"("careerId","clubId","status");
CREATE TABLE "DirectorProjectApproval" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "projectId" TEXT NOT NULL, "stakeholder" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "trustAtDecision" DOUBLE PRECISION, "condition" JSONB NOT NULL DEFAULT '{}', "decidedDay" INTEGER, "explanation" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "DirectorProjectApproval_projectId_stakeholder_key" ON "DirectorProjectApproval"("projectId","stakeholder");
CREATE TABLE "DirectorProjectFinance" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "projectId" TEXT NOT NULL, "source" TEXT NOT NULL, "amount" INTEGER NOT NULL, "interestRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "termDays" INTEGER, "installment" INTEGER, "nextDueDay" INTEGER, "remaining" INTEGER NOT NULL, "condition" JSONB NOT NULL DEFAULT '{}', "status" TEXT NOT NULL DEFAULT 'PROPOSED', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "DirectorProjectFinance_careerId_status_nextDueDay_idx" ON "DirectorProjectFinance"("careerId","status","nextDueDay");

CREATE TABLE "DirectorSupporterSegment" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "kind" TEXT NOT NULL, "size" INTEGER NOT NULL, "trust" DOUBLE PRECISION NOT NULL DEFAULT 60, "priceSensitivity" DOUBLE PRECISION NOT NULL, "sportingSensitivity" DOUBLE PRECISION NOT NULL, "identitySensitivity" DOUBLE PRECISION NOT NULL, "preferences" JSONB NOT NULL DEFAULT '{}', "conflict" DOUBLE PRECISION NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "DirectorSupporterSegment_careerId_clubId_kind_key" ON "DirectorSupporterSegment"("careerId","clubId","kind");
CREATE TABLE "DirectorTicketPolicy" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "seasonId" TEXT, "standardPrice" INTEGER NOT NULL, "familyPrice" INTEGER NOT NULL, "premiumPrice" INTEGER NOT NULL, "seasonTicket" INTEGER NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "effectiveDay" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "DirectorTicketPolicy_careerId_clubId_status_idx" ON "DirectorTicketPolicy"("careerId","clubId","status");
CREATE TABLE "DirectorAttendanceSnapshot" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "matchId" TEXT NOT NULL, "dayIndex" INTEGER NOT NULL, "capacity" INTEGER NOT NULL, "attendance" INTEGER NOT NULL, "ticketRevenue" INTEGER NOT NULL, "commercialRevenue" INTEGER NOT NULL, "segmentDemand" JSONB NOT NULL DEFAULT '{}', "explanation" JSONB NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "DirectorAttendanceSnapshot_matchId_key" ON "DirectorAttendanceSnapshot"("matchId"); CREATE INDEX "DirectorAttendanceSnapshot_careerId_clubId_dayIndex_idx" ON "DirectorAttendanceSnapshot"("careerId","clubId","dayIndex");

CREATE TABLE "DirectorAcademyTeam" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "level" TEXT NOT NULL DEFAULT 'U19', "seasonNumber" INTEGER NOT NULL, "reputation" DOUBLE PRECISION NOT NULL DEFAULT 50, "coachingQuality" DOUBLE PRECISION NOT NULL DEFAULT 50, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "DirectorAcademyTeam_careerId_clubId_level_seasonNumber_key" ON "DirectorAcademyTeam"("careerId","clubId","level","seasonNumber");
CREATE TABLE "DirectorAcademyMatch" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "teamId" TEXT NOT NULL, "seasonNumber" INTEGER NOT NULL, "round" INTEGER NOT NULL, "scheduledDay" INTEGER NOT NULL, "opponent" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'SCHEDULED', "goalsFor" INTEGER, "goalsAgainst" INTEGER, "performance" DOUBLE PRECISION, "minutes" JSONB NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "DirectorAcademyMatch_teamId_seasonNumber_round_key" ON "DirectorAcademyMatch"("teamId","seasonNumber","round"); CREATE INDEX "DirectorAcademyMatch_careerId_scheduledDay_status_idx" ON "DirectorAcademyMatch"("careerId","scheduledDay","status");
CREATE TABLE "DirectorAcademyIntake" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "seasonNumber" INTEGER NOT NULL, "dayIndex" INTEGER NOT NULL, "playerIds" JSONB NOT NULL DEFAULT '[]', "quality" DOUBLE PRECISION NOT NULL, "explanation" JSONB NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "DirectorAcademyIntake_careerId_clubId_seasonNumber_key" ON "DirectorAcademyIntake"("careerId","clubId","seasonNumber");
CREATE TABLE "DirectorAcademyPlan" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "playerId" TEXT NOT NULL, "focus" TEXT NOT NULL, "pathway" TEXT NOT NULL DEFAULT 'U19', "status" TEXT NOT NULL DEFAULT 'ACTIVE', "readiness" DOUBLE PRECISION NOT NULL DEFAULT 30, "lastReviewDay" INTEGER NOT NULL, "explanation" JSONB NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "DirectorAcademyPlan_playerId_key" ON "DirectorAcademyPlan"("playerId"); CREATE INDEX "DirectorAcademyPlan_careerId_status_idx" ON "DirectorAcademyPlan"("careerId","status");

CREATE TABLE "DirectorIdentitySnapshot" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "dayIndex" INTEGER NOT NULL, "declared" JSONB NOT NULL DEFAULT '[]', "observed" JSONB NOT NULL DEFAULT '{}', "alignment" DOUBLE PRECISION NOT NULL, "credibility" DOUBLE PRECISION NOT NULL, "drivers" JSONB NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "DirectorIdentitySnapshot_careerId_clubId_dayIndex_key" ON "DirectorIdentitySnapshot"("careerId","clubId","dayIndex");
CREATE TABLE "DirectorSponsor" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "name" TEXT NOT NULL, "sector" TEXT NOT NULL, "reputation" DOUBLE PRECISION NOT NULL, "ethics" DOUBLE PRECISION NOT NULL, "budget" INTEGER NOT NULL, "audience" TEXT NOT NULL, "requirements" JSONB NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "DirectorSponsor_careerId_sector_idx" ON "DirectorSponsor"("careerId","sector");
CREATE TABLE "DirectorSponsorOffer" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "sponsorId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "category" TEXT NOT NULL, "guaranteed" INTEGER NOT NULL, "bonus" INTEGER NOT NULL, "durationDays" INTEGER NOT NULL, "namingRights" BOOLEAN NOT NULL DEFAULT false, "exclusivity" TEXT, "conditions" JSONB NOT NULL DEFAULT '{}', "expiresDay" INTEGER NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "DirectorSponsorOffer_careerId_clubId_status_expiresDay_idx" ON "DirectorSponsorOffer"("careerId","clubId","status","expiresDay");
CREATE TABLE "DirectorSponsorContract" ("id" TEXT PRIMARY KEY, "careerId" TEXT NOT NULL, "sponsorId" TEXT NOT NULL, "clubId" TEXT NOT NULL, "offerId" TEXT, "category" TEXT NOT NULL, "guaranteed" INTEGER NOT NULL, "bonus" INTEGER NOT NULL, "startDay" INTEGER NOT NULL, "endDay" INTEGER NOT NULL, "namingRights" BOOLEAN NOT NULL DEFAULT false, "exclusivity" TEXT, "conditions" JSONB NOT NULL DEFAULT '{}', "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "DirectorSponsorContract_offerId_key" ON "DirectorSponsorContract"("offerId"); CREATE INDEX "DirectorSponsorContract_careerId_clubId_status_endDay_idx" ON "DirectorSponsorContract"("careerId","clubId","status","endDay");

ALTER TABLE "DirectorStadiumZone" ADD CONSTRAINT "DirectorStadiumZone_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE;
ALTER TABLE "DirectorCapitalProject" ADD CONSTRAINT "DirectorCapitalProject_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE;
ALTER TABLE "DirectorProjectApproval" ADD CONSTRAINT "DirectorProjectApproval_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorProjectApproval" ADD CONSTRAINT "DirectorProjectApproval_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "DirectorCapitalProject"("id") ON DELETE CASCADE;
ALTER TABLE "DirectorProjectFinance" ADD CONSTRAINT "DirectorProjectFinance_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorProjectFinance" ADD CONSTRAINT "DirectorProjectFinance_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "DirectorCapitalProject"("id") ON DELETE CASCADE;
ALTER TABLE "DirectorSupporterSegment" ADD CONSTRAINT "DirectorSupporterSegment_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorTicketPolicy" ADD CONSTRAINT "DirectorTicketPolicy_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorAttendanceSnapshot" ADD CONSTRAINT "DirectorAttendanceSnapshot_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE;
ALTER TABLE "DirectorAcademyTeam" ADD CONSTRAINT "DirectorAcademyTeam_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorAcademyMatch" ADD CONSTRAINT "DirectorAcademyMatch_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorAcademyIntake" ADD CONSTRAINT "DirectorAcademyIntake_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorAcademyPlan" ADD CONSTRAINT "DirectorAcademyPlan_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE;
ALTER TABLE "DirectorIdentitySnapshot" ADD CONSTRAINT "DirectorIdentitySnapshot_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorSponsor" ADD CONSTRAINT "DirectorSponsor_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorSponsorOffer" ADD CONSTRAINT "DirectorSponsorOffer_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorSponsorOffer" ADD CONSTRAINT "DirectorSponsorOffer_sponsorId_fkey" FOREIGN KEY ("sponsorId") REFERENCES "DirectorSponsor"("id") ON DELETE CASCADE; ALTER TABLE "DirectorSponsorContract" ADD CONSTRAINT "DirectorSponsorContract_careerId_fkey" FOREIGN KEY ("careerId") REFERENCES "DirectorCareer"("id") ON DELETE CASCADE; ALTER TABLE "DirectorSponsorContract" ADD CONSTRAINT "DirectorSponsorContract_sponsorId_fkey" FOREIGN KEY ("sponsorId") REFERENCES "DirectorSponsor"("id") ON DELETE CASCADE;
