"use client";

import { useState } from "react";
import type { DirectorDTO } from "@/lib/director/types";

type Props = { world: DirectorDTO; busy: boolean; command: (payload: object) => Promise<void> };
const PILLARS = [["ACADEMY", "Akademie"], ["LOCAL", "Lokální identita"], ["DATA", "Datový nábor"], ["SUSTAINABLE", "Udržitelnost"], ["ATTRACTIVE", "Atraktivní fotbal"], ["WIN_NOW", "Okamžitý úspěch"], ["COMMERCIAL", "Komerční růst"]] as const;

export function DirectorInfrastructure({ world, busy, command }: Props) {
  const hub = world.infrastructure;
  const [declared, setDeclared] = useState<string[]>(hub?.identity?.declared ?? []);
  const [tickets, setTickets] = useState(hub?.ticketPolicy ?? { standardPrice: 22, familyPrice: 14, premiumPrice: 75, seasonTicket: 320 });
  if (!hub) return null;
  const active = hub.projects.find((item) => item.status === "ACTIVE");
  const required = active && active.phase === "FINANCING" ? (active.approvedCost ?? active.costMax) + active.contingency : 0;
  const cash = Math.min(world.club.cashBalance, Math.round(required * .25)); const loan = Math.round(required * .5); const owner = Math.round(required * .15); const partner = Math.max(0, required - cash - loan - owner);
  return <div className="mb-4 space-y-4">
    <section className="director-panel"><div className="director-section-head"><div><p className="page-kicker">Klubový svět v7</p><h2>Finance, stadion, akademie a identita</h2></div><span className="director-status">dlouhodobá strategie</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Info label="Hotovost" value={money(world.club.cashBalance)} /><Info label="Budoucí závazky" value={money(world.finances.liabilities)} /><Info label="Zóny stadionu" value={String(hub.zones.length)} /><Info label="U19" value={`${hub.academy?.players.length ?? 0} hráčů`} /><Info label="Soulad identity" value={`${Math.round(hub.identity?.alignment ?? 50)} %`} /><Info label="Aktivní partneři" value={String(hub.sponsorContracts.filter((item) => item.status === "ACTIVE").length)} /></div></section>

    <section className="director-panel"><div className="director-section-head"><div><p className="page-kicker">Stadionový plán</p><h2>{active?.title ?? "Areál bez rozpracované investice"}</h2></div>{active && <span className="director-status">{phase(active.phase)}</span>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{hub.zones.map((zone) => <article key={zone.id} className="director-scout-card"><span>{zone.capacity ? `${zone.capacity.toLocaleString("cs-CZ")} míst` : `úroveň ${zone.level}`}</span><strong>{zone.name}</strong><p>Kvalita {Math.round(zone.quality)}/100 · stav {Math.round(zone.condition)}/100</p><small>provoz {money(zone.operatingCost)}/sezona{zone.temporaryCapacity ? ` · dočasně ${zone.temporaryCapacity} míst` : ""}</small></article>)}</div>
      {active ? <div className="director-negotiation-response mt-4"><strong>{phase(active.phase)} · odhad {money(active.costMin)}–{money(active.costMax)}</strong><p>Schváleno {active.approvedCost ? money(active.approvedCost) : "čeká se"} · rezerva {money(active.contingency)} · utraceno {money(active.spent)}{active.targetDay !== null ? ` · termín den ${active.targetDay + 1}` : ""}</p>{active.approvals.length > 0 && <p>{active.approvals.map((item) => `${item.stakeholder}: ${item.status}`).join(" · ")}</p>}{active.phase === "FINANCING" && <button disabled={busy} className="director-primary mt-3" onClick={() => command({ action: "finance_project", projectId: active.id, cash, loan, owner, partner })}>Kombinované financování · {money(required)}</button>}</div> : <div className="director-project-options mt-4">{[["PITCH", "Trávník", "modernizace povrchu"], ["ACTIVE_END", "Aktivní tribuna", "kapacita a atmosféra"], ["HOSPITALITY", "Hospitality", "prémiové příjmy"], ["EXPANSION", "Rozšíření", "vyšší kapacita"], ["NEW_STADIUM", "Nový stadion", "víceletý projekt"], ["ACADEMY", "Akademický areál", "budoucí ročníky"]].map(([kind, title, note]) => <button key={kind} disabled={busy} onClick={() => command({ action: "start_capital_project", kind })}><strong>{title}</strong><span>{note}</span></button>)}</div>}
    </section>

    <div className="director-grid"><section className="director-panel"><div className="director-section-head"><h2>Fanoušci a vstupné</h2><span className="text-xs text-muted">pět skupin</span></div>{hub.supporters.map((item) => <div key={item.kind} className="director-market-row"><span><strong>{supporter(item.kind)}</strong><small>{item.preference}</small></span><span className={item.trust >= 65 ? "positive" : item.trust < 45 ? "negative" : ""}>{Math.round(item.trust)}/100</span></div>)}<div className="mt-3 grid grid-cols-2 gap-2"><NumberField label="Běžná" value={tickets.standardPrice} set={(value) => setTickets({ ...tickets, standardPrice: value })} /><NumberField label="Rodinná" value={tickets.familyPrice} set={(value) => setTickets({ ...tickets, familyPrice: value })} /><NumberField label="Premium" value={tickets.premiumPrice} set={(value) => setTickets({ ...tickets, premiumPrice: value })} /><NumberField label="Permanentka" value={tickets.seasonTicket} set={(value) => setTickets({ ...tickets, seasonTicket: value })} /></div><button disabled={busy} className="ui-button-secondary mt-3" onClick={() => command({ action: "ticket_policy", ...tickets })}>Uložit ceny</button></section>
      <section className="director-panel"><div className="director-section-head"><h2>Klubová identita</h2><span className="director-status">důvěryhodnost {Math.round(hub.identity?.credibility ?? 50)}</span></div><p className="mt-2 text-sm text-muted">Deklaraci hra porovnává se skutečnými minutami odchovanců, přestupy, financemi, stylem a partnery.</p><div className="mt-3 flex flex-wrap gap-2">{PILLARS.map(([key, label]) => <button key={key} type="button" className={declared.includes(key) ? "ui-button-primary" : "ui-button-secondary"} onClick={() => setDeclared((items) => items.includes(key) ? items.filter((item) => item !== key) : items.length < 3 ? [...items, key] : items)}>{label}</button>)}</div><button disabled={busy} className="director-primary mt-3" onClick={() => command({ action: "update_identity", declared })}>Potvrdit pilíře</button>{hub.identity && <div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(hub.identity.observed).map(([key, value]) => <Info key={key} label={PILLARS.find((item) => item[0] === key)?.[1] ?? key} value={`${Math.round(value)}/100`} />)}</div>}</section></div>

    {hub.academy && <section className="director-panel"><div className="director-section-head"><div><p className="page-kicker">Akademie U19</p><h2>Vývoj podle minut, plánu a zázemí</h2></div><span className="director-status">trenéři {Math.round(hub.academy.coachingQuality)}/100</span></div><div className="mt-4 overflow-x-auto"><table className="director-table"><thead><tr><th>Hráč</th><th>Věk</th><th>Pozice</th><th>Síla / potenciál</th><th>Připravenost</th><th>Cesta</th><th>Akce</th></tr></thead><tbody>{hub.academy.players.map((player) => <tr key={player.id}><td><strong>{player.name}</strong><small>{player.focus} · {player.minutes} min</small></td><td>{player.age}</td><td>{player.position}</td><td>{Math.round(player.ability)} / {Math.round(player.potential)}</td><td>{Math.round(player.readiness)}/100</td><td>{player.pathway}</td><td><div className="flex gap-2"><button disabled={busy} className="text-xs underline" onClick={() => command({ action: "academy_player", playerId: player.id, command: "FIRST_TEAM_TRAINING" })}>Trénink A</button><button disabled={busy || player.readiness < 45} className="text-xs underline" onClick={() => command({ action: "academy_player", playerId: player.id, command: "PROMOTE" })}>Povýšit</button></div></td></tr>)}</tbody></table></div></section>}

    <section className="director-panel"><div className="director-section-head"><h2>Partneři</h2><span className="text-xs text-muted">garance, bonusy a podmínky</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{hub.sponsorOffers.map((offer) => <article key={offer.id} className="director-scout-card"><span>{offer.category} · etika {Math.round(offer.ethics)}/100</span><strong>{offer.sponsor}</strong><p>{money(offer.guaranteed)} garantováno · bonus {money(offer.bonus)}</p><small>do dne {offer.expiresDay + 1}{offer.namingRights ? " · práva k názvu" : ""}</small><button disabled={busy} onClick={() => command({ action: "accept_sponsor", offerId: offer.id })}>Přijmout smlouvu</button></article>)}</div>{hub.sponsorContracts.map((contract) => <div key={contract.id} className="director-market-row"><span><strong>{contract.sponsor}</strong><small>{contract.category} · do dne {contract.endDay + 1}</small></span><span>{money(contract.guaranteed)}</span></div>)}</section>
  </div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border bg-background/50 p-3"><span className="text-xs text-muted">{label}</span><strong className="mt-1 block tabular-nums">{value}</strong></div>; }
function NumberField({ label, value, set }: { label: string; value: number; set: (value: number) => void }) { return <label className="text-xs font-semibold text-muted">{label}<input className="ui-control mt-1" type="number" min="5" value={value} onChange={(event) => set(Number(event.target.value))} /></label>; }
function money(value: number) { return new Intl.NumberFormat("cs-CZ", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value); }
function phase(value: string) { return ({ INTENT: "záměr", STUDY: "studie", APPROVALS: "schvalování", FINANCING: "financování", CONSTRUCTION: "výstavba", OPERATING: "v provozu" } as Record<string, string>)[value] ?? value; }
function supporter(value: string) { return ({ CORE: "Aktivní jádro", SEASON: "Permanentkáři", FAMILY: "Rodiny", CASUAL: "Příležitostní", ONLINE: "Online fanoušci" } as Record<string, string>)[value] ?? value; }
