import type { DirectorDTO } from "@/lib/director/types";

const TONES = [
  ["FACTUAL", "Věcně"], ["DIPLOMATIC", "Diplomaticky"], ["AMBITIOUS", "Ambiciózně"],
  ["DEFENSIVE", "Defenzivně"], ["EMOTIONAL", "Emotivně"], ["NO_COMMENT", "Bez komentáře"],
] as const;

export function DirectorLivingWorld({ world, busy, command, compact = false }: { world: DirectorDTO; busy: boolean; command: (payload: object) => Promise<void>; compact?: boolean }) {
  const living = world.livingWorld; if (!living) return null; const critical = living.criticalStory;
  if (compact) return <section className="director-panel md:col-span-2"><div className="director-section-head"><div><p className="page-kicker">Živý klubový svět</p><h2>{critical?.headline ?? "Bez kritické situace"}</h2></div><span className={critical?.severity === "CRISIS" ? "director-status danger" : "director-status"}>{critical?.phase ?? "stabilní"}</span></div>{critical && <><p className="mt-2 text-sm text-muted">{critical.summary}</p>{critical.canRespond && <div className="mt-4 flex flex-wrap gap-2">{TONES.map(([tone, label]) => <button key={tone} disabled={busy} className={tone === "FACTUAL" ? "director-primary" : "ui-button-secondary"} onClick={() => command({ action: "publish_statement", storyId: critical.id, tone })}>{label}</button>)}</div>}</>}</section>;
  const investigation = living.compliance.find((item) => item.investigationId && item.investigationStatus && item.investigationStatus !== "CLOSED");
  return <div className="director-grid">
    <section className="director-panel"><p className="page-kicker">Soukromý profil ředitele</p><h2 className="mt-1">{world.career.name}</h2>{living.reputation ? <><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{Object.entries({ Sport: living.reputation.sporting, Finance: living.reputation.financial, Lidé: living.reputation.people, Vyjednávání: living.reputation.negotiation, Veřejnost: living.reputation.public, Etika: living.reputation.ethical }).map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-background/50 p-3"><span className="block text-xs text-muted">{label}</span><strong className="text-lg tabular-nums">{Math.round(value)}/100</strong></div>)}</div><p className="mt-3 text-sm"><strong>{living.reputation.archetypes.join(" · ")}</strong></p><p className="mt-1 text-xs text-muted">{living.reputation.drivers.join(" · ")}</p></> : <p className="mt-3 text-sm text-muted">Profil se vytvoří při dalším herním kroku.</p>}</section>
    <aside className="director-panel"><p className="page-kicker">Fanouškovská rada</p><h2 className="mt-1">{living.supporterCouncil.stance === "SUPPORT" ? "Podpora" : living.supporterCouncil.stance === "OPPOSE" ? "Odpor" : "Podmíněná podpora"}</h2><p className="mt-2 text-sm text-muted">Společné stanovisko pěti segmentů · skóre {Math.round(living.supporterCouncil.score)}/100.</p><div className="mt-4 space-y-2">{world.infrastructure?.supporters.map((item) => <div key={item.kind} className="flex justify-between gap-3 border-b border-border pb-2 text-xs"><span>{item.kind}</span><strong>důvěra {Math.round(item.trust)}</strong></div>)}</div></aside>
    <section className="director-panel md:col-span-2"><div className="director-section-head"><div><p className="page-kicker">Aktivní příběhy</p><h2>Příčina, rozhodnutí a následek</h2></div><span className="director-status">{living.stories.length}</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{living.stories.map((story) => <article key={story.id} className="rounded-xl border border-border bg-background/50 p-4"><span className="text-[10px] font-bold uppercase tracking-wide text-muted">{story.pack} · {story.phase}</span><strong className="mt-1 block">{story.headline}</strong><p className="mt-1 text-xs leading-relaxed text-muted">{story.summary}</p>{story.nextDueDay !== null && <small className="mt-2 block">další vývoj: den {story.nextDueDay + 1}</small>}</article>)}</div></section>
    <section className="director-panel"><h2>Stakeholdeři</h2><div className="mt-3 space-y-3">{living.actors.map((actor) => <article key={actor.id} className="director-relationship"><div><strong>{actor.name}</strong><span>{actor.kind} · vliv {Math.round(actor.influence)}</span></div><p>{actor.personality} · důvěra {Math.round(actor.trust)} · respekt {Math.round(actor.respect)}</p><small>{actor.alternatives.join(" · ")}</small></article>)}</div></section>
    <section className="director-panel"><div className="director-section-head"><h2>Compliance</h2><span className={investigation ? "director-status danger" : "director-status"}>{investigation ? "vyžaduje reakci" : "bez otevřeného prověření"}</span></div>{living.compliance.length ? living.compliance.map((item) => <div key={item.id} className="mt-3 rounded-xl border border-border p-3 text-sm"><strong>{item.kind}</strong><p className="text-xs text-muted">{item.status} · expozice {Math.round(item.exposure)}</p></div>) : <p className="mt-3 text-sm text-muted">Klub nemá otevřenou compliance stopu.</p>}{investigation && <div className="mt-4 flex flex-wrap gap-2">{[["DISCLOSE", "Zveřejnit"], ["REMEDIATE", "Napravit"], ["LEGAL_REVIEW", "Právní prověření"], ["DENY", "Odmítnout"], ["SILENCE", "Mlčet"]].map(([response, label]) => <button key={response} disabled={busy} className="ui-button-secondary" onClick={() => command({ action: "resolve_investigation", investigationId: investigation.investigationId, response })}>{label}</button>)}</div>}</section>
    <section className="director-panel md:col-span-2"><div className="director-section-head"><h2>Kariérní stopa</h2><span className="director-status">jen soukromě</span></div><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-6">{Object.entries({ Sezony: living.profile.seasons, Trofeje: living.profile.trophies, Přestupy: living.profile.completedTransfers, Odchovanci: living.profile.academyGraduates, Projekty: living.profile.stadiumProjects, Milníky: living.profile.achievements }).map(([label, value]) => <div key={label} className="rounded-xl bg-background/60 p-3"><span className="block text-xs text-muted">{label}</span><strong>{value}</strong></div>)}</div></section>
  </div>;
}
