"use client";
import { useEffect, useState } from "react";
type Leg = { fixtureId:number;kickoff:string;homeName:string;awayName:string;winnerName:string;totalSide:"OVER"|"UNDER";totalLine:number;role:string;decimalOdds:number|null;bookmaker:string|null;reason:string;eloExpectedValue?:number|null };
type Ticket = { slot:number;combinedOdds:number|null;legs:Leg[] };
type Block = { strategy:"VALUE"|"ELO_INTUITION";frozen:boolean;tickets:Ticket[];emptyReason:string|null;coverage:{fixtures:number;withOdds:number;candidates:number} };
type Payload = { date:string;strategies:Block[] };
const emptyText:Record<string,string>={WAITING_FOR_ODDS:"Čekáme na přímé kombinované kurzy.",INSUFFICIENT_ELO_HISTORY:"Týmy zatím nemají požadovaných 10 LONG a 5 FAST zápasů.",NOT_ENOUGH_CANDIDATES:"Filtry našly méně než tři kvalifikované příležitosti.",NO_VALID_COMBINATION:"Kandidáti existují, ale žádná kombinace nemá 3–4 nohy a kurz 8–30."};
const selection=(leg:Leg)=>`${leg.winnerName} + ${leg.totalSide==="OVER"?"více":"méně"} než ${String(leg.totalLine).replace(".",",")} gólu`;
function StrategyCard({block}:{block:Block}){const[slot,setSlot]=useState(1);const ticket=block.tickets.find(x=>x.slot===slot)??block.tickets[0];return <article className="overflow-hidden rounded-xl border border-border bg-surface shadow-sm"><div className="flex items-center justify-between gap-3 border-b border-border px-4 py-3"><div><p className="page-kicker">{block.strategy==="VALUE"?"Tržní value":"Oddělený experiment"}</p><strong className="text-sm text-foreground">{block.strategy==="VALUE"?"Přísný VALUE tiket":"Experimentální ELO/INTUICE"}</strong></div>{block.tickets.length>1&&<div className="flex rounded-lg border border-border p-0.5">{block.tickets.map(x=><button key={x.slot} onClick={()=>setSlot(x.slot)} className={`rounded-md px-2 py-1 text-[10px] font-bold ${x.slot===ticket?.slot?"bg-accent text-white":"text-muted"}`}>{x.slot===1?"A":"B"}</button>)}</div>}</div>{!ticket?<div className="px-4 py-5"><p className="text-sm text-foreground">{emptyText[block.emptyReason??""]??"Tiket pro toto okno nevznikl."}</p><p className="mt-1 text-[11px] text-muted">{block.coverage.withOdds}/{block.coverage.fixtures} zápasů s kurzem · {block.coverage.candidates} kandidátů</p></div>:<><div className="flex justify-between border-b border-border px-4 py-2 text-[11px] text-muted"><span>{block.frozen?"Uzamčeno":"Průběžný návrh"} · tiket {ticket.slot===1?"A":"B"}</span><strong className="text-foreground">Kurz {ticket.combinedOdds?.toFixed(2)??"—"}</strong></div><ol className="divide-y divide-border">{ticket.legs.map(leg=><li key={leg.fixtureId} className="px-4 py-3"><p className="truncate text-[10px] text-muted">{leg.homeName} – {leg.awayName} · {new Date(leg.kickoff).toLocaleString("cs-CZ",{weekday:"short",hour:"2-digit",minute:"2-digit"})}</p><div className="mt-0.5 flex justify-between gap-3"><strong className="text-sm text-foreground">{selection(leg)}</strong><span className="rounded-full bg-accent/15 px-2 py-1 text-[9px] font-bold">{leg.role==="SUPPORT"?"OPORA":leg.role}</span></div><p className="mt-1 text-[11px] text-muted">{leg.reason}</p><p className="mt-1 text-[10px] text-muted">{leg.decimalOdds?.toFixed(2)} · {leg.bookmaker}{block.strategy==="ELO_INTUITION"&&leg.eloExpectedValue!=null?` · Elo EV ${(leg.eloExpectedValue*100).toFixed(1)} %`:""}</p></li>)}</ol></>}<p className="border-t border-border bg-background px-4 py-2 text-[10px] text-muted">Sledovaný modelový výběr, nikoli doporučení vkladu. Výsledky strategií se vyhodnocují odděleně.</p></article>}
export function IntuitionTickets({date}:{date:string|null}){const[payload,setPayload]=useState<Payload|null>(null);useEffect(()=>{if(!date)return;const c=new AbortController();queueMicrotask(()=>setPayload(null));fetch(`/api/picks/intuition-tickets?date=${encodeURIComponent(date)}`,{signal:c.signal}).then(r=>r.ok?r.json() as Promise<Payload>:null).then(x=>x&&setPayload(x)).catch(()=>{});return()=>c.abort()},[date]);if(!payload)return null;return <section className="mt-4" aria-labelledby="strategy-ticket-title"><div className="mb-2"><p className="page-kicker">Sledované strategie</p><h2 id="strategy-ticket-title" className="mt-1 text-base font-extrabold text-foreground">Tikety herního okna</h2></div><div className="grid gap-3 lg:grid-cols-2">{payload.strategies.map(block=><StrategyCard key={block.strategy} block={block}/>)}</div></section>}
