import { notFound } from "next/navigation";
import { getCurrentUser } from "@/lib/authUser";
import { isAdminEmail } from "@/lib/entitlements";
import { getModelGovernanceDashboard } from "@/lib/data/modelGovernance";
import { Breadcrumbs, PageBackLink } from "@/app/_components/ui/PageNavigation";
import { ActionLink, Badge } from "@/app/_components/ui/primitives";

export const metadata = { title: "Řízení modelů | Football Insight" };
const metric = (value: number | null) => value == null ? "—" : value.toFixed(3);
const percent = (value: number) => `${Math.round(value * 100)} %`;
const statusLabel: Record<string, string> = { REVIEW: "Prověřit", WATCH: "Sledovat", PROMISING: "Slibné", LOW_SAMPLE: "Málo dat" };

function incidentMeaning(title: string) {
  if (title.startsWith("FRESH_CLOSE")) return { meaning: "Málo zápasů má čerstvý závěrečný kurz, takže CLV zatím není dostatečně spolehlivé.", action: "Zkontrolovat hodinový kurzový cron a zda poslední vzorek vzniká nejvýše 75 minut před výkopem." };
  if (title.startsWith("ODDS_SERIES_3")) return { meaning: "U většiny zápasů chybějí alespoň tři srovnatelné kurzové body.", action: "Prověřit pokračovací dávky snapshot-odds a opakování stejné linie a bookmakera." };
  if (title.startsWith("OPENING")) return { meaning: "Část zápasů nemá zachycený první dostupný kurz.", action: "Prověřit, zda první kurzový sběr běží dostatečně brzy po vytvoření predikce." };
  return { meaning: "Otevřený provozní nebo modelový incident vyžaduje kontrolu.", action: "Otevřít Provoz pipeline a zkontrolovat poslední související běh." };
}

export default async function ModelGovernancePage() {
  const user = await getCurrentUser();
  if (!user?.email || !isAdminEmail(user.email)) notFound();
  const data = await getModelGovernanceDashboard();
  return <main className="page-shell py-6">
    <header className="mb-5">
      <div className="mb-4 flex flex-wrap items-center gap-3"><PageBackLink /><Breadcrumbs items={[{ label: "Zápasy", href: "/" }, { label: "Provoz", href: "/provoz" }, { label: "Modely" }]} /></div>
      <p className="page-kicker">Administrace · Model v{data.modelVersion}</p>
      <h1 className="page-title">Řídicí centrum modelů</h1>
      <p className="mt-2 max-w-3xl text-sm text-muted">Ukazuje, co je potřeba právě teď opravit, co pouze sledovat a kdy bude dost dat pro rozhodnutí. Nic zde model automaticky nepovyšuje ani nepřelaďuje.</p>
      <AdminNav />
    </header>
    <section className="ui-panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border bg-background/60 px-4 py-3"><div><p className="page-kicker">Prioritní fronta</p><h2 className="mt-1 text-lg font-bold">Co je potřeba udělat</h2></div><Badge tone={data.tasks.some((task) => task.priority === "NOW") ? "negative" : data.tasks.length ? "warning" : "positive"}>{data.tasks.length ? `${data.tasks.length} otevřené` : "Bez zásahu"}</Badge></div>{data.tasks.length ? <div className="divide-y divide-border">{data.tasks.map((task, index) => { const help = incidentMeaning(task.title); const urgent = task.priority === "NOW"; return <article key={`${task.title}-${index}`} className={`grid gap-3 p-4 text-sm md:grid-cols-[9rem_minmax(0,1fr)] ${urgent ? "bg-negative/[.025]" : ""}`}><div><Badge tone={urgent ? "negative" : task.priority === "SOON" ? "warning" : "neutral"}>{urgent ? "Řešit nyní" : task.priority === "SOON" ? "Brzy" : "Sledovat"}</Badge><p className="mt-2 text-[10px] font-bold uppercase tracking-wide text-muted">{task.title}</p></div><div><strong className="text-foreground">{help.meaning}</strong><p className="mt-1 leading-5 text-muted">{task.reason}</p><div className="mt-3 rounded-lg border-l-4 border-accent-strong bg-background px-3 py-2"><span className="text-[10px] font-bold uppercase tracking-wide text-muted">Doporučený krok</span><p className="mt-0.5 text-xs text-foreground">{help.action}</p></div></div></article>; })}</div> : <p className="p-5 text-sm text-muted">Není splatná mimořádná kontrola. Pokračuje pravidelný sběr.</p>}</section>
    <section className="ui-panel mt-4 p-4"><h2 className="text-lg font-bold">Ochranná 1X2 shadow politika</h2><p className="mt-1 text-sm text-muted">Stejný základ jako 1X2 v2, ale vyžaduje připravenost 7. Extrémní rozdíly nad 15 p. b. ponechá pouze k auditu. Turecká liga zůstává zahrnutá.</p><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Mini label="Celkem" value={data.shadow.total} /><Mini label="Kandidáti" value={data.shadow.candidates} /><Mini label="Jen sledovat" value={data.shadow.watch} /></div></section>
    <section className="ui-panel mt-4 p-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="page-kicker">Hlavní model · shadow v{data.mainModelShadow.version}</p><h2 className="text-lg font-bold">Tržně ukotvený kandidát</h2><p className="mt-1 max-w-3xl text-sm text-muted">V8 kombinuje první dostupný odmaržený trh, současný model v7 a při dostatečné historii také Elo. Běží pouze ve stínu a ostré predikce ani tikety nemění.</p></div><Badge tone={data.mainModelShadow.verdict === "V8_BEATS_V7" ? "positive" : data.mainModelShadow.verdict === "KEEP_V7" ? "warning" : "neutral"}>{data.mainModelShadow.verdict === "COLLECT" ? "Sbírá data" : data.mainModelShadow.verdict === "V8_BEATS_V7" ? "Kandidát překonává v7" : "Ponechat v7"}</Badge></div>
      <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4 lg:grid-cols-6"><Mini label="Zachyceno" value={data.mainModelShadow.captured} /><Mini label="Vyhodnoceno" value={`${data.mainModelShadow.settled}/${data.mainModelShadow.minimumDecisionSample}`} /><Mini label="v7 log-loss" value={metric(data.mainModelShadow.source.logLoss)} /><Mini label="v8 log-loss" value={metric(data.mainModelShadow.candidate.logLoss)} /><Mini label="Otevírací trh" value={metric(data.mainModelShadow.opening.logLoss)} /><Mini label="Závěrečný trh" value={metric(data.mainModelShadow.closing.logLoss)} /></div>
      <p className="mt-3 text-xs text-muted">Rozhodnutí se provede nejdříve při 100 uzavřených zápasech na totožné prospektivní kohortě. Pokrytí závěrečným kurzem: {percent(data.mainModelShadow.closingCoverage)}. Primární metrika je log-loss; nižší hodnota je lepší.</p>
      {data.mainModelShadow.development.length ? <details className="mt-4 rounded-lg border border-border p-3" open><summary className="cursor-pointer font-semibold">Jak se v8 průběžně vyvíjí</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-muted"><tr><th>Checkpoint</th><th>Do data</th><th>v7</th><th>v8</th><th>Otevírací trh</th><th>Závěrečný trh</th><th>v8 vs v7</th></tr></thead><tbody>{data.mainModelShadow.development.map((item) => <tr className="border-t border-border" key={item.sampleSize}><td className="py-2 font-semibold">n={item.sampleSize}</td><td>{item.through?.toLocaleDateString("cs-CZ") ?? "—"}</td><td>{metric(item.sourceLogLoss)}</td><td>{metric(item.candidateLogLoss)}</td><td>{metric(item.openingLogLoss)}</td><td>{metric(item.closingLogLoss)}</td><td className={item.deltaToSource != null && item.deltaToSource < 0 ? "text-positive" : item.deltaToSource != null && item.deltaToSource > 0 ? "text-negative" : "text-muted"}>{item.deltaToSource == null ? "—" : `${item.deltaToSource > 0 ? "+" : ""}${item.deltaToSource.toFixed(3)}`}</td></tr>)}</tbody></table></div><p className="mt-2 text-xs text-muted">Záporný rozdíl v posledním sloupci znamená, že v8 má na stejné kohortě nižší log-loss než v7. Tabulka ukazuje nejvýše posledních 12 kumulativních checkpointů.</p></details> : <p className="mt-4 rounded-lg border border-dashed border-border p-3 text-sm text-muted">Vývoj se objeví po uzavření prvního zápasu se zachyceným v8 snapshotem.</p>}
    </section>
    <section className="ui-panel mt-4 p-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="page-kicker">Tvorba šancí · shadow v{data.performancePressure.version}</p><h2 className="text-lg font-bold">Tlakový a střelecký model</h2><p className="mt-1 max-w-3xl text-sm text-muted">Porovnává současný Over 2,5 s alternativou odvozenou ze střel, střel na branku, zakončení z vápna, xG a obranné zranitelnosti soupeře. Je pouze diagnostický.</p></div><Badge tone="neutral">Sbírá data</Badge></div>
      <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4 lg:grid-cols-7"><Mini label="Zachyceno" value={data.performancePressure.captured} /><Mini label="Vyhodnoceno" value={`${data.performancePressure.settled}/${data.performancePressure.minimumDecisionSample}`} /><Mini label="Pokrytí vstupů" value={percent(data.performancePressure.averageCoverage)} /><Mini label="Vysoká závislost" value={data.performancePressure.highDependency} /><Mini label="Prům. změna Over" value={data.performancePressure.averageOverDelta == null ? "—" : `${data.performancePressure.averageOverDelta >= 0 ? "+" : ""}${(data.performancePressure.averageOverDelta * 100).toFixed(1)} p. b.`} /><Mini label="Současný log-loss" value={metric(data.performancePressure.current.logLoss)} /><Mini label="Shadow log-loss" value={metric(data.performancePressure.shadow.logLoss)} /></div>
      {data.performancePressure.development.length ? <details className="mt-4 rounded-lg border border-border p-3"><summary className="cursor-pointer font-semibold">Vývoj po chronologických checkpointech</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-muted"><tr><th>Vzorek</th><th>Do data</th><th>Současný</th><th>Shadow</th><th>Rozdíl</th></tr></thead><tbody>{data.performancePressure.development.map((item) => <tr className="border-t border-border" key={item.sampleSize}><td className="py-2 font-semibold">n={item.sampleSize}</td><td>{item.through?.toLocaleDateString("cs-CZ") ?? "—"}</td><td>{metric(item.currentLogLoss)}</td><td>{metric(item.shadowLogLoss)}</td><td className={item.delta != null && item.delta < 0 ? "text-positive" : item.delta != null && item.delta > 0 ? "text-negative" : "text-muted"}>{item.delta == null ? "—" : `${item.delta > 0 ? "+" : ""}${item.delta.toFixed(3)}`}</td></tr>)}</tbody></table></div></details> : <p className="mt-4 rounded-lg border border-dashed border-border p-3 text-sm text-muted">Vyhodnocení se objeví po prvním dokončeném zápase se shadow snapshotem.</p>}
      {data.performancePressure.recent.length ? <details className="mt-4 rounded-lg border border-border p-3" open><summary className="cursor-pointer font-semibold">Poslední shadow predikce</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-muted"><tr><th>Zápas</th><th>Výkop</th><th>Index tlaku</th><th>Otevřenost</th><th>Over nyní</th><th>Over shadow</th><th>Změna</th><th>Závislost</th><th>Data</th></tr></thead><tbody>{data.performancePressure.recent.map((item) => <tr className="border-t border-border" key={item.fixtureId}><td className="py-2 font-semibold">{item.homeName} – {item.awayName}</td><td>{item.kickoff.toLocaleString("cs-CZ")}</td><td>{item.homePressure?.toFixed(0) ?? "—"} : {item.awayPressure?.toFixed(0) ?? "—"}</td><td>{item.opennessScore?.toFixed(0) ?? "—"}/100</td><td>{percent(item.currentOver25)}</td><td>{item.shadowOver25 == null ? "—" : percent(item.shadowOver25)}</td><td>{item.over25Delta == null ? "—" : `${item.over25Delta >= 0 ? "+" : ""}${(item.over25Delta * 100).toFixed(1)} p. b.`}</td><td>{item.dependencyRisk === "HIGH" ? "Vysoká" : item.dependencyRisk === "MEDIUM" ? "Střední" : "Nízká"}</td><td>{percent(item.coverage)}</td></tr>)}</tbody></table></div><p className="mt-2 text-xs text-muted">Index 100 znamená velmi silný očekávaný tlak; hodnoty nad 100 označují extrémně příznivý matchup, nejde o procenta.</p></details> : <p className="mt-4 text-sm text-muted">První řádky vzniknou po spuštění predikčního cronu s novou verzí kódu.</p>}
      <p className="mt-3 text-xs text-muted">Nižší log-loss je lepší. Rozhodovat se nebude před 200 uzavřenými point-in-time predikcemi; do té doby shadow výstup nic nekvalifikuje.</p>
    </section>
    <section className="ui-panel mt-4 p-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="page-kicker">Shadow model</p><h2 className="text-lg font-bold">Sestavy a dostupnost</h2><p className="mt-1 max-w-3xl text-sm text-muted">Historický audit dřívějšího experimentu se sestavami, absencemi a hráčskými profily. Ostré predikce ani portfolio neovlivňuje.</p></div><span className="rounded-full bg-background px-3 py-1 text-xs font-bold text-muted">Pozastaveno</span></div>
      <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4 lg:grid-cols-6"><Mini label="Podporované zápasy" value={data.personnel.fixtureCount} /><Mini label="Obě sestavy" value={data.personnel.completeFixtures} /><Mini label="Sestavy zachyceny" value={percent(data.personnel.lineupCoverage)} /><Mini label="Absence zachyceny" value={percent(data.personnel.availabilityCoverage)} /><Mini label="Hráčské profily" value={data.personnel.playerProfiles} /><Mini label="Shadow snapshoty" value={data.personnel.shadows} /></div>
      <p className="mt-3 text-sm"><strong>Stav:</strong> Automatický sběr je vypnutý kvůli nízkému přínosu vůči spotřebě API a databáze. Dosavadní snapshoty zůstávají pouze pro audit; ruční endpoint lze při budoucím návratu znovu použít.</p>
      <p className="mt-1 text-xs text-muted">Milník pro první časový fit: {data.personnel.completeFixtures}/{data.personnel.milestone} utkání. Poslední sběr: {data.personnel.latestRun?.startedAt.toLocaleString("cs-CZ") ?? "zatím neproběhl"}.</p>
      <FetchAudit attempts={data.personnel.fetchAttempts} />
      {data.personnel.recent.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-muted"><tr><th>Zápas</th><th>Výkop</th><th>Stav</th><th>Úplnost</th><th>Baseline xG</th><th>Shadow xG</th></tr></thead><tbody>{data.personnel.recent.map((item) => <tr className="border-t border-border" key={item.id}><td className="py-2 font-semibold">{item.fixture ? `${item.fixture.homeName} – ${item.fixture.awayName}` : `Fixture ${item.fixtureId}`}</td><td>{item.kickoff.toLocaleString("cs-CZ")}</td><td>{item.status}</td><td>{percent(item.completeness)}</td><td>{item.baselineLambdaHome.toFixed(2)} : {item.baselineLambdaAway.toFixed(2)}</td><td>{item.shadowLambdaHome.toFixed(2)} : {item.shadowLambdaAway.toFixed(2)}</td></tr>)}</tbody></table></div> : null}
    </section>
    <section className="ui-panel mt-4 p-4"><h2 className="text-lg font-bold">Zachycení rychlého přehledu</h2><p className="mt-1 text-sm text-muted">Diagnostika posledních sedmi dnů. Historické mezery před opravou se zpětně nevytvářejí; po nasazení musí nové kvalifikované scénáře vytvořit neměnný výběr.</p><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-5"><Mini label="Zápasy" value={data.quickOverview.eligibleFixtures} /><Mini label="Splnily model" value={data.quickOverview.qualified} /><Mini label="Zmrazeno v2" value={data.quickOverview.frozen} /><Mini label="Chyběl kurz" value={data.quickOverview.missingOdds} /><Mini label="Nezachyceno" value={data.quickOverview.notCaptured} /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-muted"><tr><th>Den</th><th>Zápasy</th><th>Modelové scénáře</th><th>Zmrazené</th><th>Bez kurzu</th><th>Nezachycené</th></tr></thead><tbody>{data.quickOverview.days.map((day) => { const qualified = day.categories.reduce((sum, row) => sum + row.qualified, 0); const frozen = day.categories.reduce((sum, row) => sum + row.frozen, 0); const missing = day.categories.reduce((sum, row) => sum + row.missingOdds, 0); const uncaptured = day.categories.reduce((sum, row) => sum + row.notCaptured, 0); return <tr className="border-t border-border" key={day.date}><td className="py-2 font-semibold">{new Date(`${day.date}T12:00:00Z`).toLocaleDateString("cs-CZ")}</td><td>{day.fixtures}</td><td>{qualified}</td><td>{frozen}</td><td>{missing}</td><td>{uncaptured}</td></tr>; })}</tbody></table></div><p className="mt-3 text-xs text-muted">Kontrolní pravidlo: u dnů po nasazení opravy nesmí zůstávat „Nezachyceno“, pokud modelová brána vyšla. Starší řádky jsou audit historického stavu, nikoliv úkol ke zpětnému doplnění.</p></section>
    <section className="ui-panel mt-4 overflow-x-auto p-4"><h2 className="text-lg font-bold">Milníky strategií</h2><table className="mt-3 w-full min-w-[760px] text-left text-sm"><thead className="text-muted"><tr><th>Model</th><th>Stav</th><th>Vzorek</th><th>Další kontrola</th><th>Co rozhodnout</th></tr></thead><tbody>{data.strategies.map((item) => <tr className="border-t border-border" key={`${item.strategy}:${item.policyVersion}`}><td className="py-2 font-semibold">{item.title}</td><td>{item.status}</td><td>{item.sample}/{item.minimumSample}</td><td>{item.nextMilestone ? `n=${item.nextMilestone} (zbývá ${item.remaining})` : "Ruční finální revize"}</td><td className="max-w-md text-xs text-muted">{item.decision}</td></tr>)}</tbody></table></section>
    <section className="ui-panel mt-4 overflow-x-auto p-4"><h2 className="text-lg font-bold">1X2 podle lig</h2><p className="mt-1 text-sm text-muted">Srovnání na totožných uzavřených zápasech. Nižší log-loss je lepší; liga se automaticky nevypíná.</p><table className="mt-3 w-full min-w-[720px] text-left text-sm"><thead className="text-muted"><tr><th>Liga</th><th>n</th><th>Model</th><th>Trh</th><th>Stav</th><th>Nízká připravenost</th></tr></thead><tbody>{data.leagues.map((league) => <tr className="border-t border-border" key={league.leagueId}><td className="py-2 font-semibold">{league.name}</td><td>{league.n}</td><td>{metric(league.modelLogLoss)}</td><td>{metric(league.marketLogLoss)}</td><td>{statusLabel[league.status]}</td><td>{league.lowReadiness}</td></tr>)}</tbody></table></section>
    <section className="ui-panel mt-4 p-4"><h2 className="text-lg font-bold">Kalibrační checkpointy</h2><div className="mt-3 grid gap-3 md:grid-cols-3">{data.checkpoints.map((item) => <article className="rounded-lg border border-border p-3 text-sm" key={`${item.cohort}:${item.modelContext}`}><strong>{item.modelContext}</strong><p className="mt-1">Čeká {item.pendingCount}/5 nových výsledků</p><p className="text-xs text-muted">Vyhodnoceno {item.evaluatedCount} · poslední běh {item.lastRunAt?.toLocaleString("cs-CZ") ?? "zatím neproběhl"}</p></article>)}</div></section>
  </main>;
}

function AdminNav() { return <nav className="mt-4 flex flex-wrap gap-2"><ActionLink variant="secondary" size="sm" href="/provoz">Provoz pipeline</ActionLink><ActionLink variant="primary" size="sm" href="/provoz/modely">Modely</ActionLink></nav>; }
function FetchAudit({ attempts }: { attempts: Array<{ id: string; attemptedAt: Date; dataType: string; status: string; endpoint: string; fixtureId: number | null; teamId: number | null; leagueId: number | null; rowCount: number | null; durationMs: number | null }> }) { return <details className="mt-4 rounded-lg border border-border p-3"><summary className="cursor-pointer font-semibold">Audit posledních fetch pokusů ({attempts.length})</summary>{attempts.length ? <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="text-muted"><tr><th>Čas</th><th>Data</th><th>Cíl</th><th>Stav</th><th>Řádků</th><th>Trvání</th></tr></thead><tbody>{attempts.map((attempt) => <tr className="border-t border-border" key={attempt.id}><td className="py-2">{attempt.attemptedAt.toLocaleString("cs-CZ")}</td><td>{attempt.dataType}</td><td>{attempt.fixtureId ? `Fixture ${attempt.fixtureId}` : attempt.teamId ? `Tým ${attempt.teamId}` : attempt.leagueId ? `Liga ${attempt.leagueId}` : attempt.endpoint}</td><td>{attempt.status}</td><td>{attempt.rowCount ?? "—"}</td><td>{attempt.durationMs == null ? "—" : `${attempt.durationMs} ms`}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-sm text-muted">Audit začal po posledním běhu sběru. Záznamy se objeví po následujícím cronu personálních dat.</p>}</details>; }
function Mini({ label, value }: { label: string; value: number | string }) { return <div className="rounded-lg bg-background p-3"><p className="text-[10px] uppercase text-muted">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
