import Link from "next/link";
import { notFound } from "next/navigation";
import { getCurrentUser } from "@/lib/authUser";
import { isAdminEmail } from "@/lib/entitlements";
import { getModelGovernanceDashboard } from "@/lib/data/modelGovernance";

export const metadata = { title: "Řízení modelů | Football Insight" };
const metric = (value: number | null) => value == null ? "—" : value.toFixed(3);
const percent = (value: number) => `${Math.round(value * 100)} %`;
const statusLabel: Record<string, string> = { REVIEW: "Prověřit", WATCH: "Sledovat", PROMISING: "Slibné", LOW_SAMPLE: "Málo dat" };

export default async function ModelGovernancePage() {
  const user = await getCurrentUser();
  if (!user?.email || !isAdminEmail(user.email)) notFound();
  const data = await getModelGovernanceDashboard();
  return <main className="page-shell py-6">
    <header className="mb-5">
      <p className="page-kicker">Administrace · Model v{data.modelVersion}</p>
      <h1 className="page-title">Řídicí centrum modelů</h1>
      <p className="mt-2 max-w-3xl text-sm text-muted">Co pohlídat, kdy vzniká dostatečný vzorek a které kohorty vyžadují kontrolu. Přehled nic automaticky nepovyšuje ani nepřelaďuje.</p>
      <AdminNav />
    </header>
    <FetchAudit attempts={data.personnel.fetchAttempts} />
    <section className="ui-panel p-4"><h2 className="text-lg font-bold">Co řešit</h2>{data.tasks.length ? <div className="mt-3 space-y-2">{data.tasks.map((task, index) => <article key={`${task.title}-${index}`} className="rounded-lg border border-border p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{task.title}</strong><span className="rounded-full bg-accent-soft px-2 py-1 text-[10px] font-bold">{task.priority === "NOW" ? "Nyní" : task.priority === "SOON" ? "Brzy" : "Sledovat"}</span></div><p className="mt-1 text-muted">{task.reason} · {task.due}</p></article>)}</div> : <p className="mt-2 text-sm text-muted">Není splatná mimořádná kontrola. Pokračuje pravidelný sběr.</p>}</section>
    <section className="ui-panel mt-4 p-4"><h2 className="text-lg font-bold">Ochranná 1X2 shadow politika</h2><p className="mt-1 text-sm text-muted">Stejný základ jako 1X2 v2, ale vyžaduje připravenost 7 a rozdíl nad 15 p. b. ponechá pouze k auditu. Turecká liga zůstává zahrnutá.</p><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Mini label="Celkem" value={data.shadow.total} /><Mini label="Kandidáti" value={data.shadow.candidates} /><Mini label="Jen sledovat" value={data.shadow.watch} /></div></section>
    <section className="ui-panel mt-4 p-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="page-kicker">Shadow model</p><h2 className="text-lg font-bold">Sestavy a dostupnost</h2><p className="mt-1 max-w-3xl text-sm text-muted">Prospektivně sbírá potvrzené sestavy, absence a hráčské profily. Ve fázi sběru nemění veřejnou predikci ani portfolio.</p></div><span className="rounded-full bg-accent-soft px-3 py-1 text-xs font-bold">{data.personnel.status === "CANDIDATE_FIT" ? "Kandidátní fit" : "Sbírá data"}</span></div>
      <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4 lg:grid-cols-6">
        <Mini label="Podporované zápasy" value={data.personnel.fixtureCount} /><Mini label="Obě sestavy" value={data.personnel.completeFixtures} /><Mini label="Lineup coverage" value={percent(data.personnel.lineupCoverage)} /><Mini label="Absence coverage" value={percent(data.personnel.availabilityCoverage)} /><Mini label="Hráčské profily" value={data.personnel.playerProfiles} /><Mini label="Shadow snapshoty" value={data.personnel.shadows} />
      </div>
      <p className="mt-3 text-xs text-muted">Milník pro první časový fit: {data.personnel.completeFixtures}/{data.personnel.milestone} utkání s potvrzenými sestavami obou týmů. Poslední sběr: {data.personnel.latestRun?.startedAt.toLocaleString("cs-CZ") ?? "zatím neproběhl"}.</p>
      {data.personnel.recent.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-muted"><tr><th>Zápas</th><th>Výkop</th><th>Stav</th><th>Úplnost</th><th>Baseline xG</th><th>Shadow xG</th></tr></thead><tbody>{data.personnel.recent.map((item) => <tr className="border-t border-border" key={item.id}><td className="py-2 font-semibold">{item.fixture ? `${item.fixture.homeName} – ${item.fixture.awayName}` : `Fixture ${item.fixtureId}`}</td><td>{item.kickoff.toLocaleString("cs-CZ")}</td><td>{item.status}</td><td>{percent(item.completeness)}</td><td>{item.baselineLambdaHome.toFixed(2)} : {item.baselineLambdaAway.toFixed(2)}</td><td>{item.shadowLambdaHome.toFixed(2)} : {item.shadowLambdaAway.toFixed(2)}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-muted">První shadow záznam vznikne po zachycení sestav obou týmů.</p>}
    </section>
    <section className="ui-panel mt-4 p-4">
      <h2 className="text-lg font-bold">Zachycení rychlého přehledu</h2>
      <p className="mt-1 text-sm text-muted">Diagnostika posledních sedmi dní. Rozlišuje kvalitní modelový scénář od skutečně zmrazeného výběru; chybějící kurz se nepovažuje za slabý model.</p>
      <div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-5"><Mini label="Zápasy" value={data.quickOverview.eligibleFixtures} /><Mini label="Splnily model" value={data.quickOverview.qualified} /><Mini label="Zmrazeno v2" value={data.quickOverview.frozen} /><Mini label="Chyběl kurz" value={data.quickOverview.missingOdds} /><Mini label="Nezachyceno" value={data.quickOverview.notCaptured} /></div>
      <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-muted"><tr><th>Den</th><th>Zápasy</th><th>Modelové scénáře</th><th>Zmrazené</th><th>Bez kurzu</th><th>Nezachycené</th></tr></thead><tbody>{data.quickOverview.days.map((day) => { const qualified = day.categories.reduce((sum, row) => sum + row.qualified, 0); const frozen = day.categories.reduce((sum, row) => sum + row.frozen, 0); const missing = day.categories.reduce((sum, row) => sum + row.missingOdds, 0); const uncaptured = day.categories.reduce((sum, row) => sum + row.notCaptured, 0); return <tr className="border-t border-border" key={day.date}><td className="py-2 font-semibold">{new Date(`${day.date}T12:00:00Z`).toLocaleDateString("cs-CZ")}</td><td>{day.fixtures}</td><td>{qualified}</td><td>{frozen}</td><td>{missing}</td><td>{uncaptured}</td></tr>; })}</tbody></table></div>
      <p className="mt-3 text-xs text-muted">„Nezachyceno“ znamená, že modelová brána vyšla a uložené kurzy existují, ale nevznikl auditní výběr v2. Takový případ vyžaduje kontrolu běhu kurzového cronu.</p>
    </section>
    <section className="ui-panel mt-4 overflow-x-auto p-4"><h2 className="text-lg font-bold">Milníky strategií</h2><table className="mt-3 w-full min-w-[760px] text-left text-sm"><thead className="text-muted"><tr><th>Model</th><th>Stav</th><th>Vzorek</th><th>Další kontrola</th><th>Co rozhodnout</th></tr></thead><tbody>{data.strategies.map((item) => <tr className="border-t border-border" key={`${item.strategy}:${item.policyVersion}`}><td className="py-2 font-semibold">{item.title}</td><td>{item.status}</td><td>{item.sample}/{item.minimumSample}</td><td>{item.nextMilestone ? `n=${item.nextMilestone} (zbývá ${item.remaining})` : "Ruční finální revize"}</td><td className="max-w-md text-xs text-muted">{item.decision}</td></tr>)}</tbody></table></section>
    <section className="ui-panel mt-4 overflow-x-auto p-4"><h2 className="text-lg font-bold">1X2 podle lig</h2><p className="mt-1 text-sm text-muted">Srovnání na totožných uzavřených zápasech. Nižší log-loss je lepší; liga se automaticky nevypíná.</p><table className="mt-3 w-full min-w-[720px] text-left text-sm"><thead className="text-muted"><tr><th>Liga</th><th>n</th><th>Model</th><th>Trh</th><th>Stav</th><th>Nízká připravenost</th></tr></thead><tbody>{data.leagues.map((league) => <tr className="border-t border-border" key={league.leagueId}><td className="py-2 font-semibold">{league.name}</td><td>{league.n}</td><td>{metric(league.modelLogLoss)}</td><td>{metric(league.marketLogLoss)}</td><td>{statusLabel[league.status]}</td><td>{league.lowReadiness}</td></tr>)}</tbody></table></section>
    <section className="ui-panel mt-4 p-4"><h2 className="text-lg font-bold">Kalibrační checkpointy</h2><div className="mt-3 grid gap-3 md:grid-cols-3">{data.checkpoints.map((item) => <article className="rounded-lg border border-border p-3 text-sm" key={`${item.cohort}:${item.modelContext}`}><strong>{item.modelContext}</strong><p className="mt-1">Čeká {item.pendingCount}/5 nových výsledků</p><p className="text-xs text-muted">Vyhodnoceno {item.evaluatedCount} · poslední běh {item.lastRunAt?.toLocaleString("cs-CZ") ?? "zatím neproběhl"}</p></article>)}</div></section>
  </main>;
}

function AdminNav() { return <nav className="mt-3 flex gap-2"><Link className="ui-button ui-button-secondary" href="/provoz">Provoz pipeline</Link><Link className="ui-button ui-button-primary" href="/provoz/modely">Modely</Link></nav>; }
function FetchAudit({ attempts }: { attempts: Array<{ id: string; attemptedAt: Date; dataType: string; status: string; endpoint: string; fixtureId: number | null; teamId: number | null; leagueId: number | null; rowCount: number | null; durationMs: number | null }> }) { return <details className="ui-panel mb-4 p-4"><summary className="cursor-pointer font-bold">Audit personĂˇlnĂ­ch fetch pokusĹŻ ({attempts.length})</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="text-muted"><tr><th>ÄŚas</th><th>Data</th><th>CĂ­l</th><th>Stav</th><th>ĹĂˇdkĹŻ</th><th>TrvĂˇnĂ­</th></tr></thead><tbody>{attempts.map((attempt) => <tr className="border-t border-border" key={attempt.id}><td className="py-2">{attempt.attemptedAt.toLocaleString("cs-CZ")}</td><td>{attempt.dataType}</td><td>{attempt.fixtureId ? `Fixture ${attempt.fixtureId}` : attempt.teamId ? `TĂ˝m ${attempt.teamId}` : attempt.leagueId ? `Liga ${attempt.leagueId}` : attempt.endpoint}</td><td>{attempt.status}</td><td>{attempt.rowCount ?? "â€”"}</td><td>{attempt.durationMs == null ? "â€”" : `${attempt.durationMs} ms`}</td></tr>)}</tbody></table></div></details>; }
function Mini({ label, value }: { label: string; value: number | string }) { return <div className="rounded-lg bg-background p-3"><p className="text-[10px] uppercase text-muted">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
