import {PrismaClient,type Prisma}from"@prisma/client";
import{computeAllValues}from"../lib/stats/aggregate";
import{gridProbs}from"../lib/stats/predict";
import{buildPerformancePressureShadow,PRESSURE_V3_CALIBRATION,type PerformancePressureShadow,type PressureContext}from"../lib/picks/performancePressureShadow";
import{buildPerformancePressureShadowV4,type PerformancePressureShadowV4}from"../lib/picks/performancePressureShadowV4";
import{buildPerformancePressureShadowV5,type PerformancePressureShadowV5}from"../lib/picks/performancePressureShadowV5";
import{PRESSURE_REPLAY_CACHE_KEY,PRESSURE_V4_REPLAY_CACHE_KEY,PRESSURE_V5_REPLAY_CACHE_KEY,summarizePressureReplay,type PressureReplayObservation,type ReplayMetricKey}from"../lib/picks/pressureReplay";
import{METRICS_BY_ENTITY,type MatchStat,type Metric}from"../lib/types";
const prisma=new PrismaClient();type Row=Prisma.MatchStatCacheGetPayload<object>;type Pressure=PerformancePressureShadow|PerformancePressureShadowV4|PerformancePressureShadowV5;const opponent=new WeakMap<Row,Row>();
const contextOf=(v:string):PressureContext=>v==="euro"?"EURO_CUP":v==="national"?"NATIONAL":"LEAGUE",metricMap:Record<ReplayMetricKey,keyof Row>={shots:"shots",shotsOnTarget:"shotsOnTarget",shotsInsideBox:"shotsInsideBox",xg:"xg",corners:"corners"},metrics=[...new Set([...METRICS_BY_ENTITY.CLUB,"XG_AGAINST","SHOTS_AGAINST","SHOTS_ON_TARGET_AGAINST","SHOTS_INSIDE_BOX_AGAINST"])]as Metric[],mean=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:null;
function toMatch(r:Row,season:number):MatchStat{const o=opponent.get(r),m:Partial<Record<Metric,number>>={};for(const[k,v]of[["GOALS_FOR",r.goalsFor],["GOALS_AGAINST",r.goalsAgainst],["CORNERS",r.corners],["SHOTS",r.shots],["XG",r.xg],["XG_AGAINST",r.xgAgainst],["SHOTS_ON_TARGET",r.shotsOnTarget],["SHOTS_INSIDE_BOX",r.shotsInsideBox],["POSSESSION",r.possession],["SHOTS_AGAINST",o?.shots??null],["SHOTS_ON_TARGET_AGAINST",o?.shotsOnTarget??null],["SHOTS_INSIDE_BOX_AGAINST",o?.shotsInsideBox??null]]as Array<[Metric,number|null]>)if(v!=null)m[k]=v;return{fixtureId:r.fixtureId,date:r.date.toISOString(),isHome:r.isHome,isNeutral:r.isNeutral,competitive:r.competitive,season:r.season,isBaseline:r.season===season-1,metrics:m}}
function lambda(h:Row[],o:Row[],venue:"HOME"|"AWAY",context:PressureContext){const own=h.filter(r=>r.isHome===(venue==="HOME")).slice(-12),opp=o.filter(r=>r.isHome!==(venue==="HOME")).slice(-12),v=[mean(own.flatMap(r=>r.xg==null?[]:[r.xg])),mean(opp.flatMap(r=>r.xgAgainst==null?[]:[r.xgAgainst])),mean(own.flatMap(r=>r.goalsFor==null?[]:[r.goalsFor])),mean(opp.flatMap(r=>r.goalsAgainst==null?[]:[r.goalsAgainst]))].filter((x):x is number=>x!=null);return Math.max(.2,Math.min(4.5,v.length?v.reduce((a,b)=>a+b,0)/v.length:context==="NATIONAL"?1.25:1.35))}
function observation(row:Row,side:"HOME"|"AWAY",hist:Row[],pressure:Pressure,context:PressureContext,full:boolean,actualShare:number):PressureReplayObservation{const shape=side==="HOME"?pressure.expectedMatchShape.home:pressure.expectedMatchShape.away,expected:PressureReplayObservation["expected"]={},actual:PressureReplayObservation["actual"]={},intervals:PressureReplayObservation["intervals"]={};for(const key of Object.keys(metricMap)as ReplayMetricKey[]){const e=shape[key],a=row[metricMap[key]];if(e.value!=null)expected[key]=e.value;if(typeof a==="number")actual[key]=a;if(e.interval)intervals[key]={low:e.interval.low,high:e.interval.high}}const teamShots=mean(hist.slice(-12).flatMap(r=>r.shots==null?[]:[r.shots])),quality=mean(hist.slice(-12).flatMap(r=>r.xg!=null&&r.shots&&r.shots>0?[r.xg/r.shots]:[])),v2=quality&&shape.xg.value!=null?Math.max(0,Math.min(40,shape.xg.value/Math.max(.05,Math.min(.3,quality)))):null;return{fixtureId:row.fixtureId,date:row.date.toISOString(),context,fidelity:full?"FULL":"PARTIAL",side,expected,actual,intervals,openness:pressure.opennessScore??0,expectedChanceShare:shape.chanceShare.value??.5,actualChanceShare:actualShare,expectedWeaker:pressure.expectedMatchShape.weakerSide===side,actualContributionShare:actualShare,historicalTeamShots:teamShots,contextShots:PRESSURE_V3_CALIBRATION[context].shots.p50,reconstructedV2Shots:v2,sample:hist.length}}
const shotsMae=(rows:PressureReplayObservation[])=>mean(rows.flatMap(r=>r.actual.shots==null||r.expected.shots==null?[]:[Math.abs(r.actual.shots-r.expected.shots)]));
const historicalShotsMae=(rows:PressureReplayObservation[])=>mean(rows.flatMap(r=>r.actual.shots==null||r.historicalTeamShots==null?[]:[Math.abs(r.actual.shots-r.historicalTeamShots)]));
const coverage=(rows:PressureReplayObservation[])=>mean(rows.flatMap(r=>r.actual.shots==null||!r.intervals.shots?[]:[r.actual.shots>=r.intervals.shots.low&&r.actual.shots<=r.intervals.shots.high?1:0]));
const direction=(rows:PressureReplayObservation[])=>mean(rows.filter(r=>r.side==="HOME"&&r.actualChanceShare!=null).map(r=>{const e=r.expectedChanceShare,a=r.actualChanceShare!;return e>=.45&&e<=.55?a>=.45&&a<=.55?1:0:(e>.55)===(a>.55)?1:0}));
type GoalMarketRow={mainOver:number;v3Over:number|null;v5Over:number;mainBtts:number;v5Btts:number;overHit:boolean;bttsHit:boolean};
const goalMarkets:GoalMarketRow[]=[];
const binaryMetrics=(rows:GoalMarketRow[],probability:(row:GoalMarketRow)=>number|null,outcome:(row:GoalMarketRow)=>boolean)=>{const points=rows.flatMap(row=>{const p=probability(row);return p==null?[]:[{p:Math.max(.001,Math.min(.999,p)),y:outcome(row)?1:0}]});if(!points.length)return{n:0,logLoss:null,brier:null,ece:null};const logLoss=mean(points.map(({p,y})=>-(y*Math.log(p)+(1-y)*Math.log(1-p)))),brier=mean(points.map(({p,y})=>(p-y)**2)),bins=Array.from({length:10},(_,i)=>points.filter(({p})=>p>=i/10&&p<(i+1)/10)),ece=bins.reduce((sum,bin)=>sum+(bin.length/points.length)*Math.abs((mean(bin.map(v=>v.p))??0)-(mean(bin.map(v=>v.y))??0)),0);return{n:points.length,logLoss,brier,ece}};
function rankStats(rows:PressureReplayObservation[]){const homes=rows.filter(r=>r.side==="HOME"),sorted=[...homes].sort((a,b)=>a.openness-b.openness),quartile=Math.floor(sorted.length/4),total=(r:PressureReplayObservation)=>{const a=rows.find(x=>x.fixtureId===r.fixtureId&&x.side==="AWAY");return r.actual.shots!=null&&a?.actual.shots!=null?r.actual.shots+a.actual.shots:null},low=mean(sorted.slice(0,quartile).flatMap(r=>total(r)==null?[]:[total(r)!])),high=mean(sorted.slice(-quartile).flatMap(r=>total(r)==null?[]:[total(r)!]));const pairs=homes.flatMap(r=>{const y=total(r);return y==null?[]:[[r.openness,y]as const]}),mx=mean(pairs.map(p=>p[0]))??0,my=mean(pairs.map(p=>p[1]))??0,num=pairs.reduce((s,[x,y])=>s+(x-mx)*(y-my),0),dx=Math.sqrt(pairs.reduce((s,[x])=>s+(x-mx)**2,0)),dy=Math.sqrt(pairs.reduce((s,[,y])=>s+(y-my)**2,0));return{correlation:dx&&dy?num/(dx*dy):null,quartileDifference:low!=null&&high!=null?high-low:null}}
async function main(){const persist=process.argv.includes("--persist"),runV5=process.argv.includes("--v5"),[rows,predictions]=await Promise.all([prisma.matchStatCache.findMany({where:{competitive:true,shots:{not:null}},orderBy:[{date:"asc"},{fixtureId:"asc"}]}),prisma.fixturePrediction.findMany({select:{fixtureId:true,kickoff:true,predictedAt:true,lambdaHome:true,lambdaAway:true,over25:true}})]),pred=new Map(predictions.map(r=>[r.fixtureId,r])),fixtures=new Map<string,Row[]>();for(const r of rows){const k=`${r.context}:${r.fixtureId}`;fixtures.set(k,[...(fixtures.get(k)??[]),r])}for(const g of fixtures.values())if(g.length===2){opponent.set(g[0],g[1]);opponent.set(g[1],g[0])}const history=new Map<string,Row[]>(),v3:PressureReplayObservation[]=[],v4:PressureReplayObservation[]=[],v5:PressureReplayObservation[]=[];let leaks=0;
for(const g of fixtures.values()){if(g.length!==2)continue;const h=g.find(r=>r.isHome),a=g.find(r=>!r.isHome);if(!h||!a)continue;const c=contextOf(h.context),hk=`${h.context}:${h.teamId}`,ak=`${a.context}:${a.teamId}`,hh=history.get(hk)??[],ah=history.get(ak)??[];if([...hh,...ah].some(r=>r.date>=h.date))leaks++;if(hh.length>=5&&ah.length>=5){const hv=computeAllValues(hh.map(r=>toMatch(r,h.season)),metrics,c==="NATIONAL"?"NATIONAL":"CLUB",h.date),av=computeAllValues(ah.map(r=>toMatch(r,a.season)),metrics,c==="NATIONAL"?"NATIONAL":"CLUB",a.date),stored=pred.get(h.fixtureId),full=!!stored&&stored.predictedAt<stored.kickoff&&stored.predictedAt<h.date,lh=full?stored!.lambdaHome:lambda(hh,ah,"HOME",c),la=full?stored!.lambdaAway:lambda(ah,hh,"AWAY",c),main=gridProbs(lh,la),over=full?stored!.over25:main.over25,p3=buildPerformancePressureShadow({homeValues:hv,awayValues:av,currentLambdaHome:lh,currentLambdaAway:la,currentOver25:over,context:c,capturedAt:h.date}),p4=buildPerformancePressureShadowV4({homeValues:hv,awayValues:av,currentLambdaHome:lh,currentLambdaAway:la,currentOver25:over,context:c,capturedAt:h.date}),p5=buildPerformancePressureShadowV5({homeValues:hv,awayValues:av,currentLambdaHome:lh,currentLambdaAway:la,currentOver25:over,context:c,capturedAt:h.date}),hs=h.xg!=null&&a.xg!=null&&h.xg+a.xg>0?h.xg/(h.xg+a.xg):h.shotsOnTarget!=null&&a.shotsOnTarget!=null&&h.shotsOnTarget+a.shotsOnTarget>0?h.shotsOnTarget/(h.shotsOnTarget+a.shotsOnTarget):h.shots!+a.shots!>0?h.shots!/(h.shots!+a.shots!):.5;if(full&&h.goalsFor!=null&&a.goalsFor!=null)goalMarkets.push({mainOver:over,v3Over:p3.shadowOver25,v5Over:p5.marketProbabilities.OVER_25,mainBtts:main.bttsYes,v5Btts:p5.marketProbabilities.BTTS_YES,overHit:h.goalsFor+a.goalsFor>=3,bttsHit:h.goalsFor>0&&a.goalsFor>0});v3.push(observation(h,"HOME",hh,p3,c,full,hs),observation(a,"AWAY",ah,p3,c,full,1-hs));v4.push(observation(h,"HOME",hh,p4,c,full,hs),observation(a,"AWAY",ah,p4,c,full,1-hs));v5.push(observation(h,"HOME",hh,p5,c,full,hs),observation(a,"AWAY",ah,p5,c,full,1-hs))}history.set(hk,[...hh,h]);history.set(ak,[...ah,a])}
const r3=summarizePressureReplay(v3),r4=summarizePressureReplay(v4),r5=summarizePressureReplay(v5),f3=v3.filter(r=>r.fidelity==="FULL"),f4=v4.filter(r=>r.fidelity==="FULL"),f5=v5.filter(r=>r.fidelity==="FULL"),candidate=runV5?f5:f4,rank=rankStats(candidate),teamMeanMae=historicalShotsMae(candidate),goalMarketBenchmarks={over25:{main:binaryMetrics(goalMarkets,r=>r.mainOver,r=>r.overHit),v3:binaryMetrics(goalMarkets,r=>r.v3Over,r=>r.overHit),v5:binaryMetrics(goalMarkets,r=>r.v5Over,r=>r.overHit)},btts:{main:binaryMetrics(goalMarkets,r=>r.mainBtts,r=>r.bttsHit),v5:binaryMetrics(goalMarkets,r=>r.v5Btts,r=>r.bttsHit)}},gates={noLeakage:leaks===0,shotsBeatV3:(shotsMae(candidate)??99)<(shotsMae(f3)??99),shotsBeatTeamMean:(shotsMae(candidate)??99)<(teamMeanMae??99),intervalCoverage:(coverage(candidate)??0)>=.75&&(coverage(candidate)??1)<=.85,opennessCorrelation:(rank.correlation??-1)>0,opennessQuartileGap:(rank.quartileDifference??-99)>=3,dominance:(direction(candidate)??0)>=.55,goalMarketsNotWorse:(goalMarketBenchmarks.over25.v5.logLoss??99)<=(goalMarketBenchmarks.over25.main.logLoss??0)+.005&&(goalMarketBenchmarks.btts.v5.logLoss??99)<=(goalMarketBenchmarks.btts.main.logLoss??0)+.005};const activated=Object.values(gates).every(Boolean),version=runV5?5:4,report={reportVersion:1,pressureVersion:version,generatedAt:new Date().toISOString(),activated,verdict:activated?"PASS":"REVIEW",gates,full:{n:candidate.length,v3ShotsMae:shotsMae(f3),candidateShotsMae:shotsMae(candidate),teamMeanShotsMae:teamMeanMae,v3Dominance:direction(f3),candidateDominance:direction(candidate),shotsCoverage80:coverage(candidate),...rank},goalMarketBenchmarks,v3:r3,v4:r4,v5:r5,leakageViolations:leaks};
if(persist){const key=runV5?PRESSURE_V5_REPLAY_CACHE_KEY:PRESSURE_V4_REPLAY_CACHE_KEY;await prisma.apiCache.upsert({where:{key},create:{key,payload:report as unknown as Prisma.InputJsonValue,expiresAt:new Date("2099-01-01")},update:{payload:report as unknown as Prisma.InputJsonValue,expiresAt:new Date("2099-01-01")}});await prisma.apiCache.upsert({where:{key:PRESSURE_REPLAY_CACHE_KEY},create:{key:PRESSURE_REPLAY_CACHE_KEY,payload:r3 as unknown as Prisma.InputJsonValue,expiresAt:new Date("2099-01-01")},update:{payload:r3 as unknown as Prisma.InputJsonValue,expiresAt:new Date("2099-01-01")}})}console.log(JSON.stringify({...report,persisted:persist},null,2))}
main().finally(()=>prisma.$disconnect());
